towers_a = {
    {
        Name = "人类·蒸汽机车",
        Ubertip = "高级的炮兵小队",
        unitSound = "SteamTank",
        file = "units\\human\\WarWagon\\WarWagon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSeigeEngine.blp",
        modelScale = 1.30,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "instant",
        Missileart = "Abilities\\Weapons\\SteamTank\\SteamTankImpact.mdl",
        cool1 = 2.75,
        Primary = "STR",
        STR = 28,
        AGI = 3,
        INT = 2,
        ATTACK_WHITE = 115,
        ATTACK_GREEN = 0
    },
    {
        Name = "人类·麦迪文",
        Ubertip = "如果当初不是被人揭发，我也是高级法师",
        unitSound = "Medivh",
        file = "units\\creeps\\Medivh\\Medivh",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMedivh.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\DruidoftheTalonMissile\\DruidoftheTalonMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        STR = 14,
        AGI = 7,
        INT = 29,
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 88
    },
    {
        Name = "矮人·狮鹫骑士",
        Ubertip = "如果我这锤子能够注入闪电的话！",
        unitSound = "GryphonRider",
        file = "units\\human\\GryphonRider\\GryphonRider",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGryphonRider.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\GryphonRiderMissile\\GryphonRiderMissile.mdl",
        cool1 = 2.00,
        Primary = "STR",
        STR = 20,
        AGI = 14,
        INT = 15,
        ATTACK_WHITE = 93,
        ATTACK_GREEN = 0
    },
    {
        Name = "矮人·狮鹫闪电骑士",
        Ubertip = "我这锤子注入了闪电！！",
        unitSound = "GryphonRider",
        file = "units\\human\\GryphonRider\\GryphonRider",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGryphonRider.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "mline",
        Missileart = "Abilities\\Spells\\Human\\StormBolt\\StormBoltMissile.mdl",
        cool1 = 1.90,
        Primary = "AGI",
        STR = 20,
        AGI = 24,
        INT = 15,
        ATTACK_WHITE = 83,
        ATTACK_GREEN = 21
    },
    {
        Name = "精灵·魔导师",
        Ubertip = "魔导给予你沉默的机会",
        unitSound = "SpellBreaker",
        file = "units\\human\\BloodElfSpellThief\\BloodElfSpellThief",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSpellBreaker.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\BloodElfSpellThiefMISSILE\\BloodElfSpellThiefMISSILE.mdl",
        cool1 = 1.85,
        Primary = "INT",
        STR = 12,
        AGI = 15,
        INT = 20,
        ATTACK_WHITE = 40,
        ATTACK_GREEN = 63
    },
    {
        Name = "兽人·攻城粉碎机",
        Ubertip = "粉碎...米分石卒...",
        unitSound = "Catapult",
        file = "units\\orc\\catapult\\catapult",
        Art = "ReplaceableTextures\\CommandButtons\\BTNDemolisher.blp",
        modelScale = 1.40,
        scale = 2.20,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "msplash",
        Missileart = "abilities\\weapons\\DemolisherMissile\\DemolisherMissile.mdl",
        cool1 = 2.85,
        Primary = "STR",
        STR = 36,
        AGI = 1,
        INT = 1,
        ATTACK_WHITE = 127,
        ATTACK_GREEN = 0
    },
    {
        Name = "兽人·白毛猛犸",
        Ubertip = "$%#..!%$..!@.%..$@!",
        unitSound = "Magnataur",
        file = "Units\\Creeps\\MagnataurBlue\\MagnataurBlue",
        Art = "ReplaceableTextures\\CommandButtons\\BTNBlueMagnataur.blp",
        modelScale = 1.70,
        scale = 2.80,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\LichMissile\\LichMissile.mdl",
        cool1 = 2.20,
        Primary = "STR",
        STR = 34,
        AGI = 20,
        INT = 3,
        ATTACK_WHITE = 97,
        ATTACK_GREEN = 0
    },
    {
        Name = "巨魔·巨魔狂战士",
        Ubertip = "丧心病狂！",
        unitSound = "HeadHunter",
        file = "units\\orc\\HeadHunter\\HeadHunter",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHeadHunter.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "abilities\\weapons\\huntermissile\\huntermissile.mdl",
        cool1 = 1.90,
        Primary = "STR",
        STR = 25,
        AGI = 19,
        INT = 3,
        ATTACK_WHITE = 90,
        ATTACK_GREEN = 0
    },
    {
        Name = "牛头人·小牛",
        Ubertip = "也有人叫我撼地者",
        unitSound = "Tauren",
        file = "units\\orc\\Tauren\\Tauren",
        Art = "ReplaceableTextures\\CommandButtons\\BTNTauren.blp",
        modelScale = 1.70,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SteamMissile\\SteamMissile.mdl",
        cool1 = 2.30,
        Primary = "STR",
        STR = 29,
        AGI = 16,
        INT = 9,
        ATTACK_WHITE = 101,
        ATTACK_GREEN = 0
    },
    {
        Name = "暗夜精灵·精灵龙",
        Ubertip = "精灵灵体化作的龙，灵异可爱",
        unitSound = "Wisp",
        file = "units\\nightelf\\FaerieDragon\\FaerieDragon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFaerieDragon.blp",
        modelScale = 1.80,
        scale = 1.30,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FaerieDragonMissile\\FaerieDragonMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        STR = 15,
        AGI = 10,
        INT = 21,
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 105,
    },
    {
        Name = "暗夜精灵·投刃车",
        Ubertip = "用树木制造的用来破坏树木的投刃车",
        unitSound = "Ballista",
        file = "units\\nightelf\\Ballista\\Ballista",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGlaiveThrower.blp",
        modelScale = 1.60,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "mbounce",
        Missileart = "Abilities\\Weapons\\GlaiveMissile\\GlaiveMissile.mdl",
        cool1 = 2.55,
        Primary = "AGI",
        STR = 12,
        AGI = 14,
        INT = 14,
        ATTACK_WHITE = 47,
        ATTACK_GREEN = 47
    },
    {
        Name = "暗夜精灵·奇美拉",
        Ubertip = "听说和哥斯拉是亲戚",
        unitSound = "Chimaera",
        file = "units\\nightelf\\Chimaera\\Chimaera",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChimaera.blp",
        modelScale = 1.30,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\ChimaeraAcidMissile\\ChimaeraAcidMissile.mdl",
        cool1 = 2.30,
        Primary = "STR",
        STR = 20,
        AGI = 13,
        INT = 17,
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 108
    },
    {
        Name = "暗夜精灵·复仇之魂",
        Ubertip = "害人之心不可有",
        unitSound = "Vengeance",
        file = "units\\nightelf\\Vengeance\\Vengeance",
        Art = "ReplaceableTextures\\CommandButtons\\BTNAvengingWatcher.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\VengeanceMissile\\VengeanceMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
        STR = 12,
        AGI = 24,
        INT = 16,
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 107
    },
    {
        Name = "德鲁伊·利爪",
        Ubertip = "听说它能变成大雄，不！是大熊",
        unitSound = "DruidOfTheClaw",
        file = "units\\nightelf\\DruidoftheClaw\\DruidoftheClaw",
        Art = "ReplaceableTextures\\CommandButtons\\BTNDruidOfTheClaw.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Objects\\Spawnmodels\\Undead\\ImpaleTargetDust\\ImpaleTargetDust.mdl",
        cool1 = 2.00,
        Primary = "STR",
        STR = 23,
        AGI = 11,
        INT = 17,
        ATTACK_WHITE = 110,
        ATTACK_GREEN = 0
    },
    {
        Name = "亡灵·绞肉车",
        Ubertip = "从不制作香肠",
        unitSound = "MeatWagon",
        file = "units\\undead\\MeatWagon\\MeatWagon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMeatWagon.blp",
        modelScale = 1.40,
        scale = 2.65,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "msplash",
        Missileart = "Abilities\\Weapons\\MeatwagonMissile\\MeatwagonMissile.mdl",
        cool1 = 2.40,
        Primary = "STR",
        STR = 26,
        AGI = 11,
        INT = 9,
        ATTACK_WHITE = 112,
        ATTACK_GREEN = 0
    },
    {
        Name = "亡灵·冰霜巨龙",
        Ubertip = "千里冰封，万里雪飘",
        unitSound = "FrostWyrm",
        file = "units\\undead\\FrostWyrm\\FrostWyrm",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFrostWyrm.blp",
        modelScale = 1.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "msplash",
        Missileart = "Abilities\\Weapons\\FrostWyrmMissile\\FrostWyrmMissile.mdl",
        cool1 = 3.00,
        Primary = "STR",
        STR = 43,
        AGI = 6,
        INT = 8,
        ATTACK_WHITE = 75,
        ATTACK_GREEN = 75
    },
    {
        Name = "海妖·皇家卫兵",
        Ubertip = "看起来就很叼的样子",
        unitSound = "NagaRoyalGuard",
        file = "units\\naga\\NagaRoyalGuard\\NagaRoyalGuard",
        Art = "ReplaceableTextures\\CommandButtons\\BTNNagaMyrmidonRoyalGuard.blp",
        modelScale = 1.50,
        scale = 2.40,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "abilities\\weapons\\WyvernSpear\\WyvernSpearMissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
        STR = 31,
        AGI = 15,
        INT = 10,
        ATTACK_WHITE = 100,
        ATTACK_GREEN = 0
    },
    {
        Name = "元素·山岭巨人",
        Ubertip = "即使是铁石组成的人也会有心灵",
        unitSound = "MountainGiant",
        file = "units\\nightelf\\MountainGiant\\MountainGiant",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMountainGiant.blp",
        modelScale = 1.10,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "msplash",
        Missileart = "Abilities\\Weapons\\AncientProtectorMissile\\AncientProtectorMissile.mdl",
        cool1 = 2.45,
        Primary = "STR",
        STR = 22,
        AGI = 12,
        INT = 18,
        ATTACK_WHITE = 110,
        ATTACK_GREEN = 0
    },
    {
        Name = "元素·撸起战棍的山岭巨人",
        Ubertip = "当铁石心肠的人撸起了又长又粗的战棍",
        unitSound = "MountainGiant",
        file = "war3mapImported\\unit_MountainGiant.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMountainGiant.blp",
        modelScale = 1.10,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "Objects\\Spawnmodels\\Undead\\ImpaleTargetDust\\ImpaleTargetDust.mdl",
        cool1 = 2.55,
        Primary = "STR",
        STR = 26,
        AGI = 11,
        INT = 19,
        ATTACK_WHITE = 135,
        ATTACK_GREEN = 0
    },
    {
        Name = "恶魔·守卫将领",
        Ubertip = "守卫...",
        unitSound = "DoomGuard",
        file = "units\\demon\\FelgaurdBlue\\FelgaurdBlue",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFelGuardBlue.blp",
        modelScale = 1.90,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\LichMissile\\LichMissile.mdl",
        cool1 = 2.10,
        Primary = "AGI",
        STR = 20,
        AGI = 30,
        INT = 6,
        ATTACK_WHITE = 95,
        ATTACK_GREEN = 0
    },
    {
        Name = "恶魔·双匕·尤迪安",
        Ubertip = "刚刚与黑暗力量立下契约，虽然力量尚未稳定，但仍然可以猎杀恶魔",
        unitSound = "HeroDemonHunter",
        file = "war3mapImported\\unit_NigheElfRogue3.mdl",
        Art = "war3mapImported\\icon_unit_Demon_Hunter.blp",
        modelScale = 2.00,
        scale = 2.10,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "",
        cool1 = 1.90,
        Primary = "AGI",
        STR = 10,
        AGI = 31,
        INT = 15,
        ATTACK_WHITE = 95,
        ATTACK_GREEN = 0
    },
}