towers_a = {
    {
        Name = "人类·蒸汽机车",
        Ubertip = "高级的炮兵小队",
        unitSound = "MortarTeam",
        file = "units\\human\\MortarTeam\\MortarTeam",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSeigeEngine.blp",
        modelScale = 1.30,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "instant",
        Missileart = "Abilities\\Weapons\\SteamTank\\SteamTankImpact.mdl",
        cool1 = 2.75,
        Primary = "STR",
        STR = 28,
        AGI = 3,
        INT = 2,
        abilList = "",
        ATTACK_WHITE = 95,
        ATTACK_GREEN = 0
    },
    {
        Name = "人类·麦迪文",
        Ubertip = "如果当初不是被人揭发，我也是高级法师",
        unitSound = "Medivh",
        file = "units\\creeps\\Medivh\\Medivh",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMedivh.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\DruidoftheTalonMissile\\DruidoftheTalonMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        STR = 14,
        AGI = 7,
        INT = 29,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 68
    },
    {
        Name = "矮人·狮鹫骑士",
        Ubertip = "如果我这锤子能够注入闪电的话！",
        unitSound = "GryphonRider",
        file = "units\\human\\GryphonRider\\GryphonRider",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGryphonRider.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 150,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\GryphonRiderMissile\\GryphonRiderMissile.mdl",
        cool1 = 2.00,
        Primary = "STR",
        STR = 20,
        AGI = 14,
        INT = 15,
        abilList = "",
        ATTACK_WHITE = 73,
        ATTACK_GREEN = 0
    },
    {
        Name = "矮人·狮鹫闪电骑士",
        Ubertip = "我这锤子注入了闪电！！",
        unitSound = "GryphonRider",
        file = "units\\human\\GryphonRider\\GryphonRider",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGryphonRider.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 150,
        weapTp1 = "mline",
        Missileart = "Abilities\\Spells\\Human\\StormBolt\\StormBoltMissile.mdl",
        cool1 = 1.90,
        Primary = "AGI",
        STR = 20,
        AGI = 24,
        INT = 15,
        abilList = "",
        ATTACK_WHITE = 73,
        ATTACK_GREEN = 11
    },
    {
        Name = "精灵·魔导师",
        Ubertip = "魔导给予你沉默的机会",
        unitSound = "SpellBreaker",
        file = "units\\human\\BloodElfSpellThief\\BloodElfSpellThief",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSpellBreaker.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\BloodElfSpellThiefMISSILE\\BloodElfSpellThiefMISSILE.mdl",
        cool1 = 1.85,
        Primary = "INT",
        STR = 12,
        AGI = 15,
        INT = 20,
        abilList = "",
        ATTACK_WHITE = 30,
        ATTACK_GREEN = 53
    },
    {
        Name = "兽人·攻城粉碎机",
        Ubertip = "粉碎...米分石卒...",
        unitSound = "Catapult",
        file = "units\\orc\\catapult\\catapult",
        Art = "ReplaceableTextures\\CommandButtons\\BTNDemolisher.blp",
        modelScale = 1.40,
        scale = 2.20,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "msplash",
        Missileart = "abilities\\weapons\\DemolisherMissile\\DemolisherMissile.mdl",
        cool1 = 2.85,
        Primary = "STR",
        STR = 36,
        AGI = 1,
        INT = 1,
        abilList = "",
        ATTACK_WHITE = 103,
        ATTACK_GREEN = 0
    },
    {
        Name = "巨魔·巨魔狂战士",
        Ubertip = "丧心病狂！",
        unitSound = "HeadHunter",
        file = "units\\orc\\HeadHunter\\HeadHunter",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHeadHunter.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "abilities\\weapons\\huntermissile\\huntermissile.mdl",
        cool1 = 1.90,
        Primary = "STR",
        STR = 25,
        AGI = 19,
        INT = 3,
        abilList = "",
        ATTACK_WHITE = 70,
        ATTACK_GREEN = 0
    },
    {
        Name = "牛头人·小牛",
        Ubertip = "也有人叫我撼地者",
        unitSound = "Tauren",
        file = "units\\orc\\Tauren\\Tauren",
        Art = "ReplaceableTextures\\CommandButtons\\BTNTauren.blp",
        modelScale = 1.70,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SteamMissile\\SteamMissile.mdl",
        cool1 = 2.30,
        Primary = "STR",
        STR = 29,
        AGI = 16,
        INT = 9,
        abilList = "",
        ATTACK_WHITE = 81,
        ATTACK_GREEN = 0
    },
    {
        Name = "暗夜精灵·精灵龙",
        Ubertip = "精灵灵体化作的龙，灵异可爱",
        unitSound = "Wisp",
        file = "units\\nightelf\\FaerieDragon\\FaerieDragon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFaerieDragon.blp",
        modelScale = 1.80,
        scale = 1.30,
        movetp = "fly",
        moveHeight = 150,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FaerieDragonMissile\\FaerieDragonMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        STR = 15,
        AGI = 10,
        INT = 21,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 85,
    },
    {
        Name = "亡灵·绞肉车",
        Ubertip = "从不制作香肠",
        unitSound = "MeatWagon",
        file = "units\\undead\\MeatWagon\\MeatWagon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMeatWagon.blp",
        modelScale = 1.40,
        scale = 2.65,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "msplash",
        Missileart = "Abilities\\Weapons\\MeatwagonMissile\\MeatwagonMissile.mdl",
        cool1 = 2.40,
        Primary = "STR",
        STR = 26,
        AGI = 10,
        INT = 6,
        abilList = "",
        ATTACK_WHITE = 92,
        ATTACK_GREEN = 0
    },
    {
        Name = "亡灵·冰霜巨龙",
        Ubertip = "千里冰封，万里雪飘",
        unitSound = "FrostWyrm",
        file = "units\\undead\\FrostWyrm\\FrostWyrm",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFrostWyrm.blp",
        modelScale = 1.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 150,
        weapTp1 = "msplash",
        Missileart = "Abilities\\Weapons\\FrostWyrmMissile\\FrostWyrmMissile.mdl",
        cool1 = 3.00,
        Primary = "STR",
        STR = 43,
        AGI = 6,
        INT = 4,
        abilList = "",
        ATTACK_WHITE = 70,
        ATTACK_GREEN = 70
    },
}