towers_b = {
    {
        Name = "人类·飞机",
        Ubertip = "无畏的飞机小队，嘟嘟嘟",
        unitSound = "Gyrocopter",
        file = "units\\human\\Gyrocopter\\Gyrocopter",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFlyingMachine.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\GyroCopter\\GyroCopterMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
        rangeN1 = 950,
        acquire = 949,
        abilList = {towerSpxKV["窥视镜"]}
    },
    {
        Name = "血精灵·女巫",
        Ubertip = "以火鸟神圣之名",
        unitSound = "Sorceress",
        file = "units\\human\\Sorceress\\Sorceress",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSorceress.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "hover",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SorceressMissile\\SorceressMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        abilList = {towerSpxKV["火球术"]}
    },
    {
        Name = "血精灵·龙鹰骑士",
        Ubertip = "这龙鹰不怎么听话",
        unitSound = "BloodElfDragonHawk",
        file = "units\\human\\BloodElfDragonHawk\\BloodElfDragonHawk",
        Art = "ReplaceableTextures\\CommandButtons\\BTNDragonHawk.blp",
        modelScale = 1.60,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\DragonHawkMissile\\DragonHawkMissile.mdl",
        cool1 = 1.90,
        Primary = "AGI",
        abilList = {towerSpxKV["震荡光弹"]}
    },
    {
        Name = "兽人·科多兽",
        Ubertip = "老是吃不饱",
        unitSound = "KotoBeast",
        file = "units\\orc\\KotoBeast\\KotoBeast",
        Art = "ReplaceableTextures\\CommandButtons\\BTNKotoBeast.blp",
        modelScale = 1.40,
        scale = 3.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Axe\\AxeMissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
        abilList = {towerSpxKV["皮糙"]}
    },
    {
        Name = "兽人·发狂科多兽",
        Ubertip = "吃不饱结果只能发狂了",
        unitSound = "KotoBeast",
        file = "units\\demon\\ChaosKotoBeast\\ChaosKotoBeast",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChaosKotoBeast.blp",
        modelScale = 1.40,
        scale = 3.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Axe\\AxeMissile.mdl",
        cool1 = 2.00,
        Primary = "STR",
        abilList = {towerSpxKV["肉燥"]}
    },
    {
        Name = "兽人·巫师",
        Ubertip = "对绿色极度的不喜欢，特别是帽子",
        unitSound = "Shaman",
        file = "units\\creeps\\ChaosWarlockGreen\\ChaosWarlockGreen",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChaosWarlockGreen.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl",
        cool1 = 2.20,
        Primary = "INT",
        abilList = {towerSpxKV["诡异闪电"]}
    },
    {
        Name = "兽人·发狂巫师",
        Ubertip = "学着别人染色纹身，装作发狂的样子的巫师",
        unitSound = "Shaman",
        file = "units\\demon\\ChaosWarlock\\ChaosWarlock",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChaosWarlock.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        abilList = {towerSpxKV["狂异闪电"]}
    },
    {
        Name = "巨魔·蝙蝠骑士",
        Ubertip = "虽然燃油很棒但我不懂灭火",
        unitSound = "TrollBatrider",
        file = "units\\orc\\BatTroll\\BatTroll",
        Art = "ReplaceableTextures\\CommandButtons\\BTNTrollBatRider.blp",
        modelScale = 1.90,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\BatTrollMissile\\BatTrollMissile.mdl",
        cool1 = 2.05,
        Primary = "AGI",
        abilList = {towerSpxKV["燃油烧弹"]}
    },
    {
        Name = "牛头人·白毛",
        Ubertip = "也有人叫我白牛",
        unitSound = "SpiritWalker",
        file = "units\\orc\\spiritwalker\\spiritwalker",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSpiritWalker.blp",
        modelScale = 2.00,
        scale = 2.40,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SteamMissile\\SteamMissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
        abilList = {towerSpxKV["灵魂净化"]}
    },
    {
        Name = "暗夜精灵·露娜",
        Ubertip = "罗马神话中月亮女神！是不可能的",
        unitSound = "Huntress",
        file = "units\\nightelf\\Huntress\\Huntress",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHuntress.blp",
        modelScale = 2.00,
        scale = 2.40,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "mbounce",
        Missileart = "Abilities\\Weapons\\SentinelMissile\\SentinelMissile.mdl",
        cool1 = 2.30,
        Primary = "AGI",
        abilList = {towerSpxKV["月刃弹射"]}
    },
    {
        Name = "德鲁伊·猛禽",
        Ubertip = "听说它能变成小鸡，不！是小鸟",
        unitSound = "DruidOfTheTalon",
        file = "units\\nightelf\\DruidoftheTalon\\DruidoftheTalon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNDruidOfTheTalon.blp",
        modelScale = 2.10,
        scale = 2.10,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\DruidoftheTalonMissile\\DruidoftheTalonMissile.mdl",
        cool1 = 2.00,
        Primary = "INT",
        abilList = {towerSpxKV["旋风"]}
    },
    {
        Name = "亡灵·石像鬼",
        Ubertip = "当石像鬼石化时，能抵御一切的魔法",
        unitSound = "Gargoyle",
        file = "units\\undead\\Gargoyle\\Gargoyle",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGargoyle.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\GargoyleMissile\\GargoyleMissile.mdl",
        cool1 = 1.90,
        Primary = "AGI",
        abilList = {towerSpxKV["石像化"]}
    },
    {
        Name = "亡灵·女妖",
        Ubertip = "未化成女妖之前的她们据说是极其具有魅力的",
        unitSound = "Banshee",
        file = "units\\undead\\Banshee\\Banshee",
        Art = "ReplaceableTextures\\CommandButtons\\BTNBanshee.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "hover",
        moveHeight = 75,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\BansheeMissile\\BansheeMissile.mdl",
        cool1 = 1.90,
        Primary = "INT",
        abilList = {towerSpxKV["魅惑"]}
    },
    {
        Name = "亡灵·僵尸",
        Ubertip = "道长在哪？",
        unitSound = "Zombie",
        file = "units\\creeps\\Zombie\\Zombie",
        Art = "ReplaceableTextures\\CommandButtons\\BTNZombie.blp",
        modelScale = 2.40,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\MeatwagonMissile\\MeatwagonMissile.mdl",
        cool1 = 1.90,
        Primary = "STR",
        abilList = {towerSpxKV["腐尸毒"]}
    },
    {
        Name = "娜迦·飞龙",
        Ubertip = "不会飞的飞龙",
        unitSound = "SnapDragon",
        file = "units\\naga\\SnapDragon\\SnapDragon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSnapDragon.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\snapMissile\\snapMissile.mdl",
        cool1 = 2.00,
        Primary = "STR",
        abilList = {towerSpxKV["蛇皮"]}
    },
    {
        Name = "娜迦·暴徒",
        Ubertip = "看起来就很怂的样子",
        unitSound = "NagaMyrmidon",
        file = "units\\naga\\NagaMyrmidon\\NagaMyrmidon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNNagaMyrmidon.blp",
        modelScale = 1.50,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SeaElementalMissile\\SeaElementalMissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
        abilList = {towerSpxKV["暴力倾向"]}
    },
    {
        Name = "元素·海人",
        Ubertip = "可以水一年的家伙",
        unitSound = "WaterElemental",
        file = "war3mapImported\\unit_SeaElemental",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSeaElemental.blp",
        modelScale = 1.80,
        scale = 2.50,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SeaElementalMissile\\SeaElementalMissile.mdl",
        cool1 = 2.20,
        Primary = "STR",
        abilList = {towerSpxKV["海洋之心"]}
    }
}
