towers_b = {
    {
        Name = "人类·飞机",
        Ubertip = "无畏的飞机小队，嘟嘟嘟",
        unitSound = "Gyrocopter",
        file = "units\\human\\Gyrocopter\\Gyrocopter",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFlyingMachine.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 150,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\GyroCopter\\GyroCopterMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
        STR = 14,
        AGI = 23,
        INT = 9,
        abilList = "",
        ATTACK_WHITE = 55,
        ATTACK_GREEN = 0
    },
    {
        Name = "精灵·女巫",
        Ubertip = "以火鸟神圣之名",
        unitSound = "Sorceress",
        file = "units\\human\\Sorceress\\Sorceress",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSorceress.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "hover",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SorceressMissile\\SorceressMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        STR = 7,
        AGI = 13,
        INT = 24,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 57
    },
    {
        Name = "精灵·龙鹰骑士",
        Ubertip = "这龙鹰不怎么听话",
        unitSound = "BloodElfDragonHawk",
        file = "units\\human\\BloodElfDragonHawk\\BloodElfDragonHawk",
        Art = "ReplaceableTextures\\CommandButtons\\BTNDragonHawk.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 150,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\DragonHawkMissile\\DragonHawkMissile.mdl",
        cool1 = 1.90,
        Primary = "AGI",
        STR = 10,
        AGI = 17,
        INT = 16,
        abilList = "",
        ATTACK_WHITE = 20,
        ATTACK_GREEN = 36
    },
    {
        Name = "兽人·科多兽",
        Ubertip = "老是吃不饱",
        unitSound = "KotoBeast",
        file = "units\\orc\\KotoBeast\\KotoBeast",
        Art = "ReplaceableTextures\\CommandButtons\\BTNKotoBeast.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Axe\\AxeMissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
        STR = 21,
        AGI = 8,
        INT = 9,
        abilList = "",
        ATTACK_WHITE = 60,
        ATTACK_GREEN = 0
    },
    {
        Name = "兽人·发狂科多兽",
        Ubertip = "吃不饱结果只能发狂了",
        unitSound = "KotoBeast",
        file = "units\\demon\\ChaosKotoBeast\\ChaosKotoBeast",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChaosKotoBeast.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Axe\\AxeMissile.mdl",
        cool1 = 2.00,
        Primary = "STR",
        STR = 26,
        AGI = 14,
        INT = 1,
        abilList = "",
        ATTACK_WHITE = 65,
        ATTACK_GREEN = 0
    },
    {
        Name = "兽人·巫师",
        Ubertip = "对绿色极度的不喜欢，特别是帽子",
        unitSound = "Shaman",
        file = "units\\creeps\\ChaosWarlockGreen\\ChaosWarlockGreen",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChaosWarlockGreen.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl",
        cool1 = 2.20,
        Primary = "INT",
        STR = 10,
        AGI = 11,
        INT = 19,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 50
    },
    {
        Name = "兽人·发狂巫师",
        Ubertip = "学着别人染色纹身，装作发狂的样子的巫师",
        unitSound = "Shaman",
        file = "units\\demon\\ChaosWarlock\\ChaosWarlock",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChaosWarlock.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        STR = 10,
        AGI = 11,
        INT = 21,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 56
    },
    {
        Name = "巨魔·蝙蝠骑士",
        Ubertip = "虽然燃油很棒但我不懂灭火",
        unitSound = "TrollBatrider",
        file = "units\\orc\\BatTroll\\BatTroll",
        Art = "ReplaceableTextures\\CommandButtons\\BTNTrollBatRider.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 150,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\BatTrollMissile\\BatTrollMissile.mdl",
        cool1 = 2.05,
        Primary = "AGI",
        STR = 16,
        AGI = 22,
        INT = 9,
        abilList = "",
        ATTACK_WHITE = 52,
        ATTACK_GREEN = 0
    },
    {
        Name = "牛头人·白毛",
        Ubertip = "也有人叫我白牛",
        unitSound = "SpiritWalker",
        file = "units\\orc\\spiritwalker\\spiritwalker",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSpiritWalker.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SteamMissile\\SteamMissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
        STR = 23,
        AGI = 16,
        INT = 14,
        abilList = "",
        ATTACK_WHITE = 39,
        ATTACK_GREEN = 20
    },
}