towers_c = {
    {
        Name = "人类·铁甲步兵",
        Ubertip = "被迫从军的步兵，坚硬挺拔",
        unitSound = "Footman",
        file = "units\\human\\Footman\\Footman",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFootman.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "abilities\\weapons\\TuskarSpear\\TuskarSpear.mdl",
        cool1 = 2.20,
        Primary = "STR",
        abilList = {towerSpxKV["铁壁"]}
    },
    {
        Name = "人类·铁甲骑兵",
        Ubertip = "升官的步兵，骑上了马",
        unitSound = "Knight",
        file = "units\\human\\Knight\\Knight",
        Art = "ReplaceableTextures\\CommandButtons\\BTNKnight.blp",
        modelScale = 1.70,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "abilities\\weapons\\TuskarSpear\\TuskarSpear.mdl",
        cool1 = 2.10,
        Primary = "STR",
        abilList = {towerSpxKV["铁壁"]}
    },
    {
        Name = "矮人·迫击炮小队",
        Ubertip = "高级的炮兵小队",
        unitSound = "MortarTeam",
        file = "units\\human\\MortarTeam\\MortarTeam",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMortarTeam.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "msplash",
        Missileart = "Abilities\\Weapons\\Mortar\\MortarMissile.mdl",
        Missilearc = 0.6,
        cool1 = 2.6,
        Primary = "STR",
        abilList = {towerSpxKV["溅射攻击"]}
    },
    {
        Name = "兽人·萨满祭司",
        Ubertip = "古老萨满的祭祀",
        unitSound = "Shaman",
        file = "units\\orc\\Shaman\\Shaman",
        Art = "ReplaceableTextures\\CommandButtons\\BTNShaman.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FarseerMissile\\FarseerMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        abilList = {towerSpxKV["净化"]}
    },
    {
        Name = "巨魔·巫医",
        Ubertip = "从没医好过人的巫医",
        unitSound = "WitchDoctor",
        file = "units\\orc\\WitchDoctor\\WitchDoctor",
        Art = "ReplaceableTextures\\CommandButtons\\BTNWitchDoctor.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\WitchDoctorMissile\\WitchDoctorMissile.mdl",
        cool1 = 2.20,
        Primary = "INT",
        abilList = {towerSpxKV["蛊毒"]}
    },
    {
        Name = "血精灵·牧师",
        Ubertip = "神啊！听我祷告",
        unitSound = "Priest",
        file = "units\\human\\Priest\\Priest",
        Art = "ReplaceableTextures\\CommandButtons\\BTNPriest.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\PriestMissile\\PriestMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        abilList = {towerSpxKV["治疗"]}
    },
    {
        Name = "暗夜精灵·树妖",
        Ubertip = "树成妖还是妖化树，这是个问题",
        unitSound = "Dryad",
        file = "units\\nightelf\\Dryad\\Dryad",
        Art = "ReplaceableTextures\\CommandButtons\\BTNDryad.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Dryadmissile\\Dryadmissile.mdl",
        cool1 = 2.20,
        Primary = "INT",
        abilList = {towerSpxKV["树木之妖"]}
    },
    {
        Name = "亡灵·地穴恶魔",
        Ubertip = "我的缠丝如思念一般",
        unitSound = "CryptFiend",
        file = "units\\undead\\CryptFiend\\CryptFiend",
        Art = "ReplaceableTextures\\CommandButtons\\BTNCryptFiend.blp",
        modelScale = 1.40,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\CryptFiendMissile\\CryptFiendMissile.mdl",
        cool1 = 2.10,
        Primary = "AGI",
        abilList = {towerSpxKV["蛛毒"]}
    },
    {
        Name = "亡灵·不死巫师",
        Ubertip = "确实会死的不死族巫师",
        unitSound = "Necromancer",
        file = "units\\undead\\Necromancer\\Necromancer",
        Art = "ReplaceableTextures\\CommandButtons\\BTNNecromancer.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\NecromancerMissile\\NecromancerMissile.mdl",
        cool1 = 2.20,
        Primary = "INT",
        abilList = {towerSpxKV["冥想"]}
    },
    {
        Name = "亡灵·飞艇",
        Ubertip = "这是一艘沉默的飞艇",
        unitSound = "",
        file = "units\\undead\\UndeadAirBarge\\UndeadAirBarge",
        Art = "ReplaceableTextures\\CommandButtons\\BTNUndeadAirBarge.blp",
        modelScale = 1.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\CannonTowerMissile\\CannonTowerMissile.mdl",
        cool1 = 2.30,
        Primary = "AGI",
        RangeInc = 100,
        abilList = {towerSpxKV["黑管火炮"]}
    },
    {
        Name = "娜迦·塞壬",
        Ubertip = "听说有的海妖会唱歌",
        unitSound = "NagaSiren",
        file = "Units\\Naga\\NagaSiren\\NagaSiren",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSeaWitch.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\WaterElementalMissile\\WaterElementalMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
        abilList = {towerSpxKV["海洋之心"]}
    },
    {
        Name = "娜迦·唱歌的塞壬",
        Ubertip = "整天无所事事唱歌的海妖",
        unitSound = "NagaSiren",
        file = "Units\\Naga\\NagaSummoner\\NagaSummoner",
        Art = "ReplaceableTextures\\CommandButtons\\BTNNagaSummoner.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\WaterElementalMissile\\WaterElementalMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
        abilList = {towerSpxKV["塞壬之歌"]}
    },
    {
        Name = "元素·海元素",
        Ubertip = "可以水一个月的家伙",
        unitSound = "WaterElemental",
        file = "Units\\Creeps\\SeaElemental\\SeaElemental",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSeaElemental.blp",
        modelScale = 1.60,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SeaElementalMissile\\SeaElementalMissile.mdl",
        cool1 = 2.20,
        Primary = "STR",
        abilList = {towerSpxKV["水之元素"]}
    }
}
