towers_c = {
    {
        Name = "人类·铁甲剑士",
        Ubertip = "升官的步兵，得到了佩剑",
        unitSound = "HighElfSwordman",
        file = "units\\human\\TheCaptain\\TheCaptain",
        Art = "ReplaceableTextures\\CommandButtons\\BTNTheCaptain.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "abilities\\weapons\\TuskarSpear\\TuskarSpear.mdl",
        cool1 = 2.00,
        Primary = "STR",
        STR = 15,
        AGI = 12,
        INT = 9,
        abilList = "",
        ATTACK_WHITE = 40,
        ATTACK_GREEN = 0
    },
    {
        Name = "人类·铁甲骑兵",
        Ubertip = "升官的步兵，骑上了马",
        unitSound = "Knight",
        file = "units\\human\\Knight\\Knight",
        Art = "ReplaceableTextures\\CommandButtons\\BTNKnight.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "abilities\\weapons\\TuskarSpear\\TuskarSpear.mdl",
        cool1 = 2.10,
        Primary = "STR",
        STR = 16,
        AGI = 13,
        INT = 7,
        abilList = "",
        ATTACK_WHITE = 43,
        ATTACK_GREEN = 0
    },
    {
        Name = "人类·迫击炮小队",
        Ubertip = "高级的炮兵小队",
        unitSound = "MortarTeam",
        file = "units\\human\\MortarTeam\\MortarTeam",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMortarTeam.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "msplash",
        Missileart = "Abilities\\Weapons\\Mortar\\MortarMissile.mdl",
        Missilearc = 0.6,
        cool1 = 2.70,
        Primary = "STR",
        STR = 30,
        AGI = 4,
        INT = 7,
        abilList = "",
        ATTACK_WHITE = 63,
        ATTACK_GREEN = 0
    },
    {
        Name = "兽人·萨满祭司",
        Ubertip = "古老萨满的祭祀",
        unitSound = "Shaman",
        file = "units\\orc\\Shaman\\Shaman",
        Art = "ReplaceableTextures\\CommandButtons\\BTNShaman.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FarseerMissile\\FarseerMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        STR = 13,
        AGI = 10,
        INT = 15,
        abilList = "",
        ATTACK_WHITE = 23,
        ATTACK_GREEN = 24
    },
    {
        Name = "巨魔·巫医",
        Ubertip = "从没医好过人的巫医",
        unitSound = "WitchDoctor",
        file = "units\\orc\\WitchDoctor\\WitchDoctor",
        Art = "ReplaceableTextures\\CommandButtons\\BTNWitchDoctor.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FarseerMissile\\FarseerMissile.mdl",
        cool1 = 2.20,
        Primary = "INT",
        STR = 12,
        AGI = 11,
        INT = 17,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 43
    },
    {
        Name = "精灵·牧师",
        Ubertip = "神啊！听我祷告",
        unitSound = "Priest",
        file = "units\\human\\Priest\\Priest",
        Art = "ReplaceableTextures\\CommandButtons\\BTNPriest.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\PriestMissile\\PriestMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        STR = 13,
        AGI = 10,
        INT = 22,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 42
    },
}
