towers_d = {
    {
        Name = "人类·铁甲步兵",
        Ubertip = "被迫从军的步兵，坚硬挺拔",
        unitSound = "Footman",
        file = "units\\human\\Footman\\Footman",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFootman.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "abilities\\weapons\\TuskarSpear\\TuskarSpear.mdl",
        cool1 = 2.20,
        Primary = "STR",
    },
    {
        Name = "人类·术士",
        Ubertip = "修炼法术的人",
        unitSound = "HumanMage",
        file = "units\\creeps\\HumanMage\\HumanMage",
        Art = "ReplaceableTextures\\CommandButtons\\BTNBanditMage.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "horse",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\PriestMissile\\PriestMissile.mdl",
        cool1 = 2.20,
        Primary = "INT",
    },
    {
        Name = "兽人·步兵",
        Ubertip = "由于智齿太大而饱受苦恼",
        unitSound = "Grunt",
        file = "units\\orc\\Grunt\\Grunt",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGrunt.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Axe\\AxeMissile.mdl",
        cool1 = 2.30,
        Primary = "STR",
    },
    {
        Name = "兽人·发狂步兵",
        Ubertip = "智齿！痛！",
        unitSound = "ChaosGrunt",
        file = "units\\demon\\ChaosGrunt\\ChaosGrunt",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChaosGrunt.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Axe\\AxeMissile.mdl",
        cool1 = 2.20,
        Primary = "STR",
    },
    {
        Name = "兽人·狼骑",
        Ubertip = "兄弟们，出发掠夺罗",
        unitSound = "Wolfrider",
        file = "units\\orc\\WolfRider\\WolfRider",
        Art = "ReplaceableTextures\\CommandButtons\\BTNRaider.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Spells\\Orc\\Ensnare\\EnsnareMissile.mdl",
        cool1 = 2.10,
        Primary = "AGI",
    },
    {
        Name = "兽人·发狂狼骑",
        Ubertip = "兄弟们，疯狂掠夺罗",
        unitSound = "Wolfrider",
        file = "units\\demon\\ChaosWolfRider\\ChaosWolfRider",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChaosWolfRider.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Spells\\Orc\\Ensnare\\EnsnareMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
    },
    {
        Name = "兽人·风骑士",
        Ubertip = "疾风之骑士",
        unitSound = "WyvernRider",
        file = "units\\orc\\WyvernRider\\WyvernRider",
        Art = "ReplaceableTextures\\CommandButtons\\BTNWyvernRider.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "missile",
        Missileart = "abilities\\weapons\\WyvernSpear\\WyvernSpearMissile.mdl",
        cool1 = 2.00, 
        Primary = "AGI",
    },
    {
        Name = "血精灵·弓箭手",
        Ubertip = "拿到弓箭而欢喜的弱弱弓箭手",
        unitSound = "Archer",
        file = "units\\creeps\\HighElfArcher\\HighElfArcher",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHighElvenArcher.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Arrow\\ArrowMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
    },
    {
        Name = "矮人·火枪手",
        Ubertip = "能够持枪的士兵，期盼出人头地的一天",
        unitSound = "Rifleman",
        file = "units\\human\\Rifleman\\Rifleman",
        Art = "ReplaceableTextures\\CommandButtons\\BTNRifleman.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "instant",
        Missileart = "Abilities\\Weapons\\Rifle\\RifleImpact.mdl",
        cool1 = 2.00,
        Primary = "AGI",
    },
    {
        Name = "暗夜精灵·弓箭手",
        Ubertip = "隐匿在树间却不射击的弓箭手",
        unitSound = "Archer",
        file = "units\\nightelf\\Archer\\Archer",
        Art = "ReplaceableTextures\\CommandButtons\\BTNArcher.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Arrow\\ArrowMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
    },
    {
        Name = "暗夜精灵·角鹰弓箭手",
        Ubertip = "在角鹰上耀武扬威却不射击的弓箭手",
        unitSound = "RiddenHippogryph",
        file = "units\\nightelf\\RiddenHippogryph\\RiddenHippogryph",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHippogriffRider.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Arrow\\ArrowMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
    },
    {
        Name = "亡灵·憎恶",
        Ubertip = "大肠都流出来了~",
        unitSound = "Abomination",
        file = "units\\undead\\Abomination\\Abomination",
        Art = "ReplaceableTextures\\CommandButtons\\BTNAbomination.blp",
        modelScale = 1.40,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "SharedModels\\Bones1.mdl",
        cool1 = 2.40,
        Primary = "STR",
    },
    {
        Name = "亡灵·十胜石雕像",
        Ubertip = "一种坚固的雕像",
        unitSound = "ObsidianStatue",
        file = "units\\undead\\ObsidianStatue\\ObsidianStatue",
        Art = "ReplaceableTextures\\CommandButtons\\BTNObsidianStatue.blp",
        modelScale = 1.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FarseerMissile\\FarseerMissile.mdl",
        cool1 = 2.40,
        Primary = "INT",
    },
    {
        Name = "亡灵·骷髅魔法师",
        Ubertip = "我的眼睛是能量体,你信吗？",
        unitSound = "Skeleton",
        file = "units\\undead\\SkeletonMage\\SkeletonMage",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSkeletonMage.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SkeletalMageMissile\\SkeletalMageMissile.mdl",
        cool1 = 2.35,
        Primary = "INT",
    },
    {
        Name = "娜迦·穆格尔鱼战士",
        Ubertip = "娜迦族的穆格尔大条鱼",
        unitSound = "Murloc",
        file = "Units\\Creeps\\MurgulReaver\\MurgulReaver",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMurgulTideWarrior.blp",
        modelScale = 2.00,
        scale = 1.80,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\WaterElementalMissile\\WaterElementalMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
    },
    {
        Name = "娜迦·龙龟",
        Ubertip = "龟壳上全是刺",
        unitSound = "GiantSeaTurtle",
        file = "Units\\Creeps\\DragonSeaTurtleRange\\DragonSeaTurtleRange",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSeaTurtleRed.blp",
        modelScale = 1.00,
        scale = 2.50,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\WaterElementalMissile\\WaterElementalMissile.mdl",
        cool1 = 2.00,
        Primary = "STR",
    },
    {
        Name = "元素·水元素",
        Ubertip = "可以水一天的家伙",
        unitSound = "WaterElemental",
        file = "units\\human\\WaterElemental\\WaterElemental",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSummonWaterElemental.blp",
        modelScale = 1.60,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\WaterElementalMissile\\WaterElementalMissile.mdl",
        cool1 = 2.10,
        Primary = "AGI",
    },
    {
        Name = "元素·漆影之狼",
        Ubertip = "黑夜构造的狼，栩栩如生",
        unitSound = "SpiritWolf",
        file = "units\\orc\\Spiritwolf\\Spiritwolf",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSpiritWolf.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\AvengerMissile\\AvengerMissile.mdl",
        cool1 = 2.10,
        Primary = "AGI",
    },
    {
        Name = "元素·树精",
        Ubertip = "ki！ki！",
        unitSound = "Ent",
        file = "units\\nightelf\\Ent\\Ent",
        Art = "ReplaceableTextures\\CommandButtons\\BTNEnt.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\AncientProtectorMissile\\AncientProtectorMissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
    }
}
