towers_e = {
    {
        Name = "人类·农民",
        Ubertip = "能力平凡的耕田农民",
        unitSound = "Peasant",
        file = "units\\human\\Peasant\\Peasant",
        Art = "ReplaceableTextures\\CommandButtons\\BTNPeasant.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl",
        cool1 = 2.00,
        Primary = "STR",
        STR = 7,
        AGI = 6,
        INT = 7,
        abilList = "",
        ATTACK_WHITE = 15,
        ATTACK_GREEN = 0
    },
    {
        Name = "人类·民兵",
        Ubertip = "强迫上武装的农民，能力依然平凡",
        unitSound = "Peasant",
        file = "units\\human\\Militia\\Militia",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMilitia.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl",
        cool1 = 2.00,
        Primary = "STR",
        STR = 11,
        AGI = 6,
        INT = 9,
        abilList = "",
        ATTACK_WHITE = 23,
        ATTACK_GREEN = 0
    },
    {
        Name = "人类·刺客",
        Ubertip = "自称刺客的土匪大哥",
        unitSound = "Bandit",
        file = "units\\creeps\\BanditSpearThrower\\BanditSpearThrower",
        Art = "ReplaceableTextures\\CommandButtons\\BTNBanditSpearThrower.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
        STR = 5,
        AGI = 3,
        INT = 4,
        abilList = "",
        ATTACK_WHITE = 36,
        ATTACK_GREEN = 0
    },
    {
        Name = "兽人·苦力",
        Ubertip = "兽人的苦力，敏捷和工资都很低",
        unitSound = "Peon",
        file = "units\\orc\\Peon\\Peon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNPeon.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl",
        cool1 = 2.20,
        Primary = "STR",
        STR = 15,
        AGI = 3,
        INT = 6,
        abilList = "",
        ATTACK_WHITE = 22,
        ATTACK_GREEN = 0
    },
    {
        Name = "兽人·发狂苦力",
        Ubertip = "兽人的苦力，由于工资太低而发狂",
        unitSound = "Peon",
        file = "units\\demon\\ChaosPeon\\ChaosPeon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChaosPeon.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
        STR = 18,
        AGI = 6,
        INT = 1,
        abilList = "",
        ATTACK_WHITE = 24,
        ATTACK_GREEN = 0
    },
    {
        Name = "兽人·豺狼战士",
        Ubertip = "我是豺狼，不是财狼",
        unitSound = "Gnoll",
        file = "units\\creeps\\GnollArcher\\GnollArcher",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGnollArcher.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\PoisonArrow\\PoisonArrowMissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
        STR = 10,
        AGI = 8,
        INT = 1,
        abilList = "",
        ATTACK_WHITE = 27,
        ATTACK_GREEN = 0
    },
    {
        Name = "精灵·血精灵工程师",
        Ubertip = "自称工程师的血精灵",
        unitSound = "Wisp",
        file = "units\\critters\\HighElfPeasant\\HighElfPeasant",
        Art = "ReplaceableTextures\\CommandButtons\\BTNBloodElfPeasant.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FaerieDragonMissile\\FaerieDragonMissile.mdl",
        cool1 = 2.00,
        Primary = "INT",
        STR = 7,
        AGI = 6,
        INT = 12,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 23
    },
    {
        Name = "亡灵·侍僧",
        Ubertip = "从不敲经拜佛的僧侣",
        unitSound = "Acolyte",
        file = "units\\undead\\Acolyte\\Acolyte",
        Art = "ReplaceableTextures\\CommandButtons\\BTNBloodElfPeasant.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\AvengerMissile\\AvengerMissile.mdl",
        cool1 = 2.20,
        Primary = "INT",
        STR = 2,
        AGI = 3,
        INT = 15,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 26
    },
    {
        Name = "亡灵·食尸鬼",
        Ubertip = "嚼食腐肉的尸鬼，神奇吧",
        unitSound = "Ghoul",
        file = "units\\undead\\Ghoul\\Ghoul",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGhoul.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "SharedModels\\Bones1.mdl",
        cool1 = 2.00,
        Primary = "AGI",
        STR = 4,
        AGI = 9,
        INT = 2,
        abilList = "",
        ATTACK_WHITE = 33,
        ATTACK_GREEN = 0
    },
    {
        Name = "亡灵·骷髅战士",
        Ubertip = "觉得有点饿，虽然没有胃",
        unitSound = "Skeleton",
        file = "units\\undead\\Skeleton\\Skeleton",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSkeletonWarrior.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "SharedModels\\Bones1.mdl",
        cool1 = 2.20,
        Primary = "STR",
        STR = 16,
        AGI = 5,
        INT = 1,
        abilList = "",
        ATTACK_WHITE = 22,
        ATTACK_GREEN = 0
    },
    {
        Name = "暗夜精灵·小精灵",
        Ubertip = "灵体，空灵有爱",
        unitSound = "Wisp",
        file = "units\\nightelf\\Wisp\\Wisp",
        Art = "ReplaceableTextures\\CommandButtons\\BTNWisp.blp",
        modelScale = 1.60,
        scale = 1.60,
        movetp = "hover",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FaerieDragonMissile\\FaerieDragonMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        STR = 6,
        AGI = 4,
        INT = 14,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 24
    },
    {
        Name = "娜迦·穆格尔小鱼",
        Ubertip = "娜迦族的穆格尔小鱼",
        unitSound = "Murloc",
        file = "units\\creeps\\MurgulSlave\\MurgulSlave",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMurgalSlave.blp",
        modelScale = 2.00,
        scale = 1.80,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\WaterElementalMissile\\WaterElementalMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
        STR = 10,
        AGI = 14,
        INT = 4,
        abilList = "",
        ATTACK_WHITE = 25,
        ATTACK_GREEN = 0
    },
    {
        Name = "地精·人工小子",
        Ubertip = "我...是个...机器...人",
        unitSound = "ClockwerkGoblin",
        file = "Units\\Creeps\\HeroTinkerRobot\\HeroTinkerRobot",
        Art = "ReplaceableTextures\\CommandButtons\\BTNClockWerkGoblin.blp",
        modelScale = 2.00,
        scale = 1.80,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "abilities\\weapons\\WyvernSpear\\WyvernSpearMissile.mdl",
        cool1 = 2.30,
        Primary = "STR",
        STR = 30,
        AGI = 1,
        INT = 1,
        abilList = "",
        ATTACK_WHITE = 45,
        ATTACK_GREEN = 0
    }
}
