towers_e = {
    {
        Name = "人类·农民",
        Ubertip = "普通的农民，能力平凡",
        unitSound = "Peasant",
        file = "units\\human\\Peasant\\Peasant",
        Art = "ReplaceableTextures\\CommandButtons\\BTNPeasant.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl",
        cool1 = 2.00,
        Primary = "STR",
        STR = 9,
        AGI = 7,
        INT = 8,
        abilList = "",
        ATTACK_WHITE = 20,
        ATTACK_GREEN = 0,
    },
    {
        Name = "兽人·苦力",
        Ubertip = "兽人的苦力，敏捷很低",
        unitSound = "Peon",
        file = "units\\orc\\Peon\\Peon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNPeon.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl",
        cool1 = 2.20,
        Primary = "STR",
        STR = 12,
        AGI = 5,
        INT = 7,
        abilList = "",
        ATTACK_WHITE = 22,
        ATTACK_GREEN = 0,
    },
    {
        Name = "精灵·小精灵",
        Ubertip = "精灵灵体，空灵有爱",
        unitSound = "Wisp",
        file = "units\\nightelf\\Wisp\\Wisp",
        Art = "ReplaceableTextures\\CommandButtons\\BTNWisp.blp",
        modelScale = 1.60,
        scale = 1.60,
        movetp = "hover",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Banditmissile\\Banditmissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        STR = 6,
        AGI = 4,
        INT = 14,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 24,
    },
}