towersMap = {
    primary = {
        STR = "力量",
        AGI = "敏捷",
        INT = "智力",
    },
    weaponType = {
        missile = "箭矢",
        msplash = "箭矢(溅射)",
        mbounce = "箭矢(弹射)",
        mline = "箭矢(穿透)",
        normal = "近战",
        instant = "立即",
        artillery = "炮火",
        aline = "炮火(穿透)",
    },
    weaponSound = {
        MetalHeavyBash = "金属重击",
        MetalMediumBash = "金属中击",
        MetalHeavyChop = "金属重砍",
        MetalMediumChop = "金属中砍",
        MetalLightChop = "金属轻砍",
        MetalHeavySlice = "金属重切",
        MetalMediumSlice = "金属中切",
        MetalLightSlice = "金属轻切",
        AxeMediumChop = "斧头中砍",
        RockHeavyBash = "岩石重击",
        WoodHeavyBash = "木头重击",
        WoodMediumBash = "木头中击",
        WoodLightBash = "木头轻击",
    },
    moveType = {
        foot = "步行",
        horse = "坐骑",
        fly = "飞行",
        hover = "浮空",
        float = "漂浮",
        amph = "两栖",
    },
}