towers_s = {
    {
        Name = "人类·全能骑士·格雷戈里",
        Ubertip = "人族王国的第一骑士长，刚正不阿",
        unitSound = "HeroPaladin",
        file = "units\\human\\HeroPaladinBoss2\\HeroPaladinBoss2",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHeroPaladin.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "",
        cool1 = 2.00,
        Primary = "STR",
        STR = 24,
        AGI = 17,
        INT = 18,
        abilList = "",
        ATTACK_WHITE = 186,
        ATTACK_GREEN = 0,
    },
    {
        Name = "人类·大法师·安东尼",
        Ubertip = "人族王国首席水系魔法使，骑着小马神出鬼没",
        unitSound = "HeroArchMage",
        file = "units\\human\\HeroArchMage\\HeroArchMage",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHeroArchMage.blp",
        modelScale = 1.80,
        scale = 2.00,
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl",
        cool1 = 2.00,
        Primary = "INT",
        STR = 19,
        AGI = 14,
        INT = 28,
        abilList = "",
        ATTACK_WHITE = 0,
        ATTACK_GREEN = 208
    },
    {
        Name = "矮人·山丘之王·波尔",
        Ubertip = "矮人族暴力狂王者，时常冲锋陷阵",
        unitSound = "HeroMountainKing",
        file = "units\\human\\HeroMountainKing\\HeroMountainKing",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHeroMountainKing.blp",
        modelScale = 1.00,
        scale = 1.00,
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "",
        cool1 = 2.20,
        Primary = "STR",
        STR = 24,
        AGI = 17,
        INT = 18,
        abilList = "",
        ATTACK_WHITE = 186,
        ATTACK_GREEN = 0,
    },
    {
        Name = "暗夜精灵·复仇天神",
        Ubertip = "防人之心不可无",
        unitSound = "SpiritOfVengeance",
        file = "units\\nightelf\\SpiritOfVengeance\\SpiritOfVengeance",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSpiritOfVengeance.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SpiritOfVengeanceMissile\\SpiritOfVengeanceMissile.mdl",
        cool1 = 1.90,
        Primary = "AGI",
        STR = 27,
        AGI = 30,
        INT = 19,
        abilList = "",
        ATTACK_WHITE = 45,
        ATTACK_GREEN = 147
    },
    {
        Name = "元素·地狱火",
        Ubertip = "地狱之火组成的人形，听起来就很厉害",
        unitSound = "Infernal",
        file = "units\\demon\\Infernal\\Infernal",
        Art = "ReplaceableTextures\\CommandButtons\\BTNInfernal.blp",
        modelScale = 1.70,
        scale = 3.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\DemonHunterMissile\\DemonHunterMissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
        STR = 31,
        AGI = 14,
        INT = 18,
        abilList = "",
        ATTACK_WHITE = 151,
        ATTACK_GREEN = 50
    },
    {
        Name = "恶魔·狂暴的守卫将领",
        Ubertip = "破坏...",
        unitSound = "DoomGuard",
        file = "units\\demon\\Felgaurd\\Felgaurd",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFelGuard.blp",
        modelScale = 1.90,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\LichMissile\\LichMissile.mdl",
        cool1 = 2.00,
        Primary = "STR",
        STR = 35,
        AGI = 20,
        INT = 7,
        abilList = "",
        ATTACK_WHITE = 210,
        ATTACK_GREEN = 0
    },
    {
        Name = "恶魔·毁灭守卫",
        Ubertip = "毁灭...",
        unitSound = "DoomGuard",
        file = "units\\demon\\DoomGuard\\DoomGuard",
        Art = "ReplaceableTextures\\CommandButtons\\BTNDoomGuard.blp",
        modelScale = 1.90,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\DemonHunterMissile\\DemonHunterMissile.mdl",
        cool1 = 2.10,
        Primary = "STR",
        STR = 32,
        AGI = 11,
        INT = 19,
        abilList = "",
        ATTACK_WHITE = 100,
        ATTACK_GREEN = 100
    },
}