towers_s = {
    {
        Name = "兽人·狂暴的守卫将领",
        Ubertip = "破坏...",
        unitSound = "DoomGuard",
        file = "units\\demon\\Felgaurd\\Felgaurd",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFelGuard.blp",
        modelScale = 1.90,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\LichMissile\\LichMissile.mdl",
        cool1 = 2.00,
        Primary = "STR",
        STR = 35,
        AGI = 20,
        INT = 7,
        abilList = "",
        ATTACK_WHITE = 210,
        ATTACK_GREEN = 0
    },
    {
        Name = "暗夜精灵·复仇天神",
        Ubertip = "防人之心不可无",
        unitSound = "SpiritOfVengeance",
        file = "units\\nightelf\\SpiritOfVengeance\\SpiritOfVengeance",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSpiritOfVengeance.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SpiritOfVengeanceMissile\\SpiritOfVengeanceMissile.mdl",
        cool1 = 1.90,
        Primary = "AGI",
        STR = 13,
        AGI = 30,
        INT = 19,
        abilList = "",
        ATTACK_WHITE = 45,
        ATTACK_GREEN = 147
    },
}