towers_ss = {
    {
        Name = "人类·海军船长·普洛特",
        Ubertip = "威风的海上将军，驾驭海船",
        unitSound = "Proudmoore",
        file = "units\\other\\Proudmoore\\Proudmoore",
        Art = "war3mapImported\\icon_unit_Captain.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\WaterElementalMissile\\WaterElementalMissile.mdl",
        cool1 = 2.20,
        Primary = "STR"
    },
    {
        Name = "人类·军团指挥官·查理",
        Ubertip = "曾是万军统领，造反作乱而沦落至此的加理瑟斯，为了隐藏自己，改为查理",
        unitSound = "Garithos",
        file = "units\\creeps\\LordGarithos\\LordGarithos",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGarithos.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "horse",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Axe\\AxeMissile.mdl",
        cool1 = 2.10,
        Primary = "STR"
    },
    {
        Name = "人类·冰雪之心·莉莉安",
        Ubertip = "魔法学院的杰出青年，最为擅长冰系魔法",
        unitSound = "Jaina",
        file = "units\\human\\Jaina\\Jaina",
        Art = "ReplaceableTextures\\CommandButtons\\BTNJaina.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_freezingsplinter.mdl",
        cool1 = 2.10,
        Primary = "INT"
    },
    {
        Name = "人类·烈焰之爱·莉莉丝",
        Ubertip = "把你烧成灰烬只为了表达我对你的爱，烈火，雄心",
        unitSound = "Sorceress",
        file = "war3mapImported\\unit_HighElfPriestess.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSorceress.blp",
        modelScale = 2.00,
        scale = 2.10,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_FireArrow.mdl",
        cool1 = 2.00,
        Primary = "INT"
    },
    {
        Name = "人类·钢铁女·埃希",
        Ubertip = "钢铁就像是她的身体的一部分，冷冷冰冰",
        unitSound = "VillagerWoman",
        file = "war3mapImported\\unit_IronQueen81x.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFemaleElfVillager.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "hover",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_speed_slash4.mdl",
        cool1 = 2.00,
        Primary = "STR"
    },
    {
        Name = "人类·屠龙女手·琳达恩",
        Ubertip = "距离上一次屠龙已经过去10年了",
        unitSound = "VillagerWoman",
        file = "war3mapImported\\unit_Lady_Liadrin.mdl",
        Art = "war3mapImported\\icon_unit_Dark_Ranger_Wandering.blp",
        modelScale = 2.20,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_spur_arrow.mdl",
        cool1 = 2.00,
        Primary = "STR"
    },
    {
        Name = "血精灵·追风者·西瓦娜斯",
        Ubertip = "来去如风的游侠，机动力和攻击力爆炸",
        unitSound = "Sylvanus",
        file = "units\\creeps\\SylvanusWindrunner\\SylvanusWindrunner",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSylvanusWindrunner.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
        cool1 = 1.80,
        Primary = "AGI"
    },
    {
        Name = "矮人·山羊骑士·穆拉吉",
        Ubertip = "山羊哟～回来罗～撞他！",
        unitSound = "HumanMage",
        file = "war3mapImported\\unit_HeroStormstrider.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNBanditMage.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\Axe\\AxeMissile.mdl",
        cool1 = 2.00,
        Primary = "INT"
    },
    {
        Name = "兽人·地狱咆哮·格罗姆",
        Ubertip = "勇猛非凡的兽人神兵，力大无比又敏捷灵动",
        unitSound = "Grom",
        file = "units\\orc\\Hellscream\\Hellscream",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHellScream.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Coup_de_Grace_Green.mdl",
        cool1 = 2.00,
        Primary = "STR"
    },
    {
        Name = "兽人·邪鬼咆哮·格烈姆",
        Ubertip = "狂热爆炸的兽人神兵，力大无穷但性格极其狂暴",
        unitSound = "Grom",
        file = "units\\demon\\ChaosHellscream\\ChaosHellscream",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChaosGrom.blp",
        modelScale = 1.70,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        Missilespeed = 0,
        Missilearc = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Coup_de_Grace.mdl",
        cool1 = 2.00,
        Primary = "STR"
    },
    {
        Name = "兽人·斧王·玛格",
        Ubertip = "善于在战场上挥斧作战，呼唤野兽之力来进行强化，既敏捷又异常勇猛",
        unitSound = "Beastmaster",
        file = "Units\\Creeps\\Beastmaster\\Beastmaster",
        Art = "ReplaceableTextures\\CommandButtons\\BTNBeastMaster.blp",
        modelScale = 1.80,
        scale = 2.30,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\RexxarMissile\\RexxarMissile.mdl",
        cool1 = 2.00,
        Primary = "STR"
    },
    {
        Name = "兽人·剑圣·赤血",
        Ubertip = "以血戍武，赤剑天涯",
        unitSound = "HeroBladeMaster",
        file = "units\\demon\\HeroChaosBladeMaster\\HeroChaosBladeMaster",
        Art = "ReplaceableTextures\\CommandButtons\\BTNChaosBlademaster.blp",
        modelScale = 1.70,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_bloodthirsty.mdl",
        cool1 = 2.00,
        Primary = "STR",
        abilList = {towerSpxKV["剑圣"]}
    },
    {
        Name = "兽人·雷神·萨尔",
        Ubertip = "在雷暴之日，引闪于锤，雷神萨尔降世",
        unitSound = "Thrall",
        file = "units\\orc\\Thrall\\Thrall",
        Art = "ReplaceableTextures\\CommandButtons\\BTNThrall.blp",
        modelScale = 1.70,
        scale = 2.40,
        movetp = "horse",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Spells\\Human\\StormBolt\\StormBoltMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI"
    },
    {
        Name = "巨魔·狂魂猎手·阿拉烈",
        Ubertip = "变得狂暴及上头，绝对不放过敌人的可怕猎人",
        unitSound = "HeadHunter",
        file = "war3mapImported\\unit_HeroVoljinGlowyEyes.mdl",
        Art = "war3mapImported\\icon_unit_HeroVoljin.blp",
        modelScale = 1.60,
        scale = 2.20,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_WarchiefMissile.mdl",
        cool1 = 2.10,
        Primary = "AGI",
        abilList = {towerSpxKV["捕猎者"], towerSpxKV["狂魂狩猎"]}
    },
    {
        Name = "巨魔·邪眼·沃尔京",
        Ubertip = "没什么东西能蒙骗沃尔京的邪眼",
        unitSound = "WitchDoctor",
        file = "war3mapImported\\unit_SenJin.mdl",
        Art = "war3mapImported\\icon_unit_Senjin.blp",
        modelScale = 1.80,
        scale = 2.20,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\WitchDoctorMissile\\WitchDoctorMissile.mdl",
        cool1 = 2.10,
        Primary = "INT",
        abilList = {towerSpxKV["巫术"], towerSpxKV["邪眼"]}
    },
    {
        Name = "暗夜精灵·月之女神·泰兰德",
        Ubertip = "高洁优美的月光女祭司，骑着她那威武的白虎",
        unitSound = "HeroMoonPriestess",
        file = "units\\nightelf\\HeroMoonPriestess\\HeroMoonPriestess",
        Art = "ReplaceableTextures\\CommandButtons\\BTNPriestessOfTheMoon.blp",
        modelScale = 1.60,
        scale = 2.80,
        movetp = "horse",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
        cool1 = 1.90,
        Primary = "AGI",
        abilList = {towerSpxKV["猫头鹰怒视"], towerSpxKV["月神强击"]}
    },
    {
        Name = "暗夜精灵·守望者·玛维",
        Ubertip = "只有最强大的意志才能让人追踪邪恶，进入黑暗的深渊而不受恶魔之力的诱惑",
        unitSound = "HeroWarden",
        file = "units\\nightelf\\herowarden\\herowarden",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHeroWarden.blp",
        modelScale = 2.00,
        scale = 2.30,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\WardenMissile\\WardenMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI"
    },
    {
        Name = "德鲁伊·先知·玛尔",
        Ubertip = "德鲁伊族人，玛尔对时空法术有他独特的见解",
        unitSound = "MalFurion",
        file = "units\\nightelf\\MalFurion\\MalFurion",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFurion.blp",
        modelScale = 2.00,
        scale = 2.50,
        movetp = "horse",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_CrystalMissile.mdl",
        cool1 = 2.20,
        Primary = "INT"
    },
    {
        Name = "亡灵·巫妖·奥丁",
        Ubertip = "神秘的巫妖族，据说曾经有巫妖成为过世界的王",
        unitSound = "HeroLich",
        file = "units\\undead\\HeroLich\\HeroLich",
        Art = "ReplaceableTextures\\CommandButtons\\BTNLichVersion2.blp",
        modelScale = 1.90,
        scale = 2.25,
        movetp = "hover",
        moveHeight = 30.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\LichMissile\\LichMissile.mdl",
        cool1 = 2.10,
        Primary = "INT"
    },
    {
        Name = "亡灵·超渡师·克尔苏加德",
        Ubertip = "专门超渡幽魂的克尔苏加德，本身也作为亡灵就是了",
        unitSound = "KelThuzadNecro",
        file = "units\\undead\\Kelthuzad\\Kelthuzad",
        Art = "ReplaceableTextures\\CommandButtons\\BTNKelThuzad.blp",
        modelScale = 2.00,
        scale = 2.10,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\NecromancerMissile\\NecromancerMissile.mdl",
        cool1 = 2.30,
        Primary = "INT"
    },
    {
        Name = "亡灵·黑夜游侠·鬼歌",
        Ubertip = "复活的游侠被黑暗所控制，从而获得了更胜以往的力量",
        unitSound = "DarkRanger",
        file = "war3mapImported\\unit_Banshee_Queen_Sylvanas.mdl",
        Art = "war3mapImported\\icon_unit_Dark_Ranger_Gradient.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "Abilities\\Spells\\Other\\BlackArrow\\BlackArrowMissile.mdl",
        cool1 = 1.95,
        Primary = "AGI"
    },
    {
        Name = "亡灵·鬼枪·但丁",
        Ubertip = "如果一枪敌人没有死，那就认真地再补一枪",
        unitSound = "Acolyte",
        file = "war3mapImported\\unit_GunAcolyte2.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNAcolyte.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "instant",
        Missileart = "Abilities\\Weapons\\GyroCopter\\GyroCopterImpact.mdl",
        cool1 = 2.00,
        Primary = "AGI"
    },
    {
        Name = "亡灵·火焰剑鬼·K",
        Ubertip = "没有人知道K的本名，只知道他剑上无情的火焰，燃尽一切",
        unitSound = "HeroDeathLord",
        file = "war3mapImported\\unit_Wrathincarnation.mdl",
        Art = "war3mapImported\\icon_unit_ShadowInfernal.blp",
        modelScale = 1.80,
        scale = 2.20,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Fireball_Minor.mdl",
        cool1 = 2.20,
        Primary = "AGI"
    },
    {
        Name = "娜迦·海龙骑士·艾萨拉",
        Ubertip = "骑着大海之龙的艾萨拉，作战力也是双倍的得力",
        unitSound = "NagaSiren",
        file = "war3mapImported\\unit_SirenWaterDragonV1.01.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSeaWitch.blp",
        modelScale = 1.70,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 120.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Azul_Arrow.mdl",
        cool1 = 2.00,
        Primary = "AGI"
    },
    {
        Name = "恶魔·觉醒猎手·尤迪安",
        Ubertip = "逐渐领悟黑暗力量，没有视觉也不再要紧，死亡是那样的清晰",
        unitSound = "EvilIllidan",
        file = "units\\nightelf\\EvilIllidan\\IllidanEvil",
        Art = "ReplaceableTextures\\CommandButtons\\BTNEvilIllidan.blp",
        modelScale = 1.60,
        scale = 2.10,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_animeslashfinal.mdl",
        cool1 = 1.70,
        Primary = "AGI"
    },
    {
        Name = "幽魂·安东尼",
        Ubertip = "曾是人族王国首席水系魔法使，通过时空之轮折射在现世的另一时空灵魂",
        unitSound = "HeroArchMage",
        file = "units\\other\\HeroArchMageGhost\\HeroArchMageGhost",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGhostMage.blp",
        modelScale = 1.80,
        scale = 2.00,
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl",
        cool1 = 2.00,
        Primary = "INT"
    },
    {
        Name = "幽魂·克尔苏加德",
        Ubertip = "虚幻的巫妖族",
        unitSound = "KelThuzadLich",
        file = "units\\undead\\KelThuzadGhost\\KelThuzadGhost",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGhostOfKelThuzad.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\NecromancerMissile\\NecromancerMissile.mdl",
        cool1 = 2.30,
        Primary = "INT"
    },
    {
        Name = "幽魂·赛纳留斯",
        Ubertip = "受尽折磨而死去的，通过时空之轮折射在现世的赛纳留斯灵魂",
        unitSound = "HeroKeeperOfTheGrove",
        file = "units\\nightelf\\HeroKeeperoftheGroveGhost\\HeroKeeperoftheGroveGhost",
        Art = "ReplaceableTextures\\CommandButtons\\BTNKeeperGhostBlue.blp",
        modelScale = 1.80,
        scale = 2.70,
        movetp = "horse",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SorceressMissile\\SorceressMissile.mdl",
        cool1 = 2.20,
        Primary = "INT"
    },
    {
        Name = "昆虫·猩红刀盔·科鲁斯",
        Ubertip = "一种发着血色的甲虫类，性格狂暴冷酷，嗜血如命",
        unitSound = "Lobstrokk",
        file = "war3mapImported\\unit_BloodBeetle.mdl",
        Art = "war3mapImported\\icon_unit_Hunter_Pet_Silithid.blp",
        modelScale = 1.20,
        scale = 2.60,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Coup_de_Grace.mdl",
        cool1 = 2.00,
        Primary = "STR"
    },
    {
        Name = "元素·海冰凛魂",
        Ubertip = "于冰封之地从海洋中诞生，一切尽毁于寒",
        unitSound = "Revenant",
        file = "war3mapImported\\unit_IceCrownOverlord.mdl",
        Art = "war3mapImported\\icon_unit_Frozen_Spirit.blp",
        modelScale = 1.90,
        scale = 2.60,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_forst_arrow.mdl",
        cool1 = 2.00,
        Primary = "AGI"
    },
    {
        Name = "元素·霹雳电魔",
        Ubertip = "雷电的化身",
        unitSound = "",
        file = "war3mapImported\\unit_NakedLightning.mdl",
        Art = "war3mapImported\\icon_unit_IcyGhostA.blp",
        modelScale = 1.40,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FarseerMissile\\FarseerMissile.mdl",
        cool1 = 1.65,
        Primary = "AGI",
        abilList = "Alit"
    },
    {
        Name = "元素·暗无天日",
        Ubertip = "...........",
        unitSound = "",
        file = "war3mapImported\\unit_ShadowGOLEM.mdl",
        Art = "war3mapImported\\icon_unit_Black.blp",
        modelScale = 1.90,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\AvengerMissile\\AvengerMissile.mdl",
        cool1 = 1.80,
        Primary = "INT"
    },
    {
        Name = "异兽·朱雀",
        Ubertip = "涅磐重生的东方神兽，诞生于熊熊烈焰之中",
        unitSound = "Phoenix",
        file = "units\\human\\phoenix\\phoenix",
        Art = "war3mapImported\\icon_unit_Phoenix.blp",
        modelScale = 1.70,
        scale = 2.00,
        movetp = "fly",
        moveHeight = 225.00,
        armor = "Flesh",
        Missileart = "Abilities\\Weapons\\PhoenixMissile\\Phoenix_Missile.mdl",
        weapTp1 = "msplash",
        cool1 = 2.00,
        Primary = "STR",
        abilList = {towerSpxKV["溅射攻击"]}
    },
    {
        Name = "地精·炼金术士·卡奈",
        Ubertip = "时常有人认错食人魔是术士本人，其实上面那只地精才是本体",
        unitSound = "HEROGoblinALCHEMIST",
        file = "Units\\Creeps\\HeroGoblinAlchemist\\HeroGoblinAlchemist",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHeroAlchemist.blp",
        modelScale = 1.55,
        scale = 2.4,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Spells\\Other\\Transmute\\GoldBottleMissile.mdl",
        cool1 = 2.10,
        Primary = "STR"
    },
    {
        Name = "食人魔·守墓人·阿尔玛",
        Ubertip = "我最讨厌的就是弟弟阿卡玛，一旦没钱他就打族人的坟墓主意",
        unitSound = "Dreanei",
        file = "war3mapImported\\unit_ArchDruidLostOneV1.02.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNDranaiMage.blp",
        modelScale = 1.90,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\HarpyMissile\\HarpyMissile.mdl",
        cool1 = 2.10,
        Primary = "INT"
    }
}
