towers_sss = {
    {
        Name = "人王·骑士王·诺克斯",
        Ubertip = "人类的统领，诺克斯，战场上仅仅存在即可令族人士气提升",
        unitSound = "Uther",
        file = "war3mapImported\\unit_ArthasMenethilKingHorseV1.01.mdl",
        Art = "war3mapImported\\icon_unit_SanguineWarlord.blp",
        modelScale = 1.90,
        scale = 2.10,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_spur_arrow2.mdl",
        cool1 = 1.90,
        Primary = "STR",
    },
    {
        Name = "人类·流浪人·风",
        Ubertip = "我的人虽然在这里，但我的心一直在放浪～",
        unitSound = "SpellBreaker",
        file = "war3mapImported\\unit_Necromancer.mdl",
        Art = "war3mapImported\\icon_unit_Mage_StudentOfTheMind.blp",
        modelScale = 2.00,
        scale = 2.20,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\IllidanMissile\\IllidanMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
    },
    {
        Name = "人王·御龙剑神·奥米伽",
        Ubertip = "别人都喊我暴龙杀手",
        unitSound = "SpellBreaker",
        file = "war3mapImported\\unit_DullahanOmega.mdl",
        Art = "war3mapImported\\icon_unit_overlord.blp",
        modelScale = 1.20,
        scale = 2.20,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Firebolt_Rough_Major.mdl",
        cool1 = 2.00,
        Primary = "STR",
    },
    {
        Name = "血精灵·影刺客·瞬",
        Ubertip = "别担心我这次用的是刀背",
        unitSound = "Satyr",
        file = "war3mapImported\\unit_HeroBEArcaneHuntress.mdl",
        Art = "war3mapImported\\icon_unit_ArcaneHuntress.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_EnergyBlade.mdl",
        cool1 = 1.60,
        Primary = "AGI",
    },
    {
        Name = "兽人·狼拳·格格塔诺",
        Ubertip = "与狼共鸣，披着银狼皮毛施展强而有力的拳击大王,虽然体型重但行动如狼一般迅猛",
        unitSound = "KotoBeast",
        file = "war3mapImported\\unit_WolfLord1.38.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGrunt.blp",
        modelScale = 1.80,
        scale = 2.40,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\unit_WolfHeadProjectile109.mdl",
        cool1 = 1.90,
        Primary = "STR",
    },
    {
        Name = "亡灵·黑狱游侠·鬼歌",
        Ubertip = "被黑暗完全吞噬的游侠，如同黑影女王一般",
        unitSound = "DarkRanger",
        file = "war3mapImported\\unit_TheBansheeQueen.mdl",
        Art = "war3mapImported\\icon_unit_Dark_Ranger_Degenerate.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "Abilities\\Spells\\Other\\BlackArrow\\BlackArrowMissile.mdl",
        cool1 = 1.85,
        Primary = "AGI",
    },
    {
        Name = "亡灵·冰骨龙魂·弗里萨",
        Ubertip = "从万丈冰骇中凝聚的龙的灵魂，诞生了冰霜骨龙这一奇妙的非生物",
        unitSound = "FrostWyrm",
        file = "war3mapImported\\unit_FrostArchon.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFrostWyrm.blp",
        modelScale = 1.40,
        scale = 2.60,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_FrostOrb.mdl",
        cool1 = 2.00,
        Primary = "INT",
    },
    {
        Name = "恶魔·阿克蒙德",
        Ubertip = "跨越了时间与空间降临，以背叛之名，行违君之事",
        unitSound = "KelThuzadNecro",
        file = "units\\demon\\Warlock\\Warlock",
        Art = "ReplaceableTextures\\CommandButtons\\BTNArchimonde.blp",
        modelScale = 2.00,
        scale = 2.40,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "msplash",
        Missileart = "Abilities\\Spells\\Undead\\DeathCoil\\DeathCoilMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
    },
    {
        Name = "恶魔·基尔加丹",
        Ubertip = "跨越了时间与空间降临，以违君之名，行背叛之事",
        unitSound = "Varimathras",
        file = "units\\demon\\Kiljaeden\\Kiljaeden",
        Art = "ReplaceableTextures\\CommandButtons\\BTNKiljaedin.blp",
        modelScale = 2.00,
        scale = 2.40,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "msplash",
        Missileart = "war3mapImported\\eff_DarkSoul.mdl",
        cool1 = 2.00,
        Primary = "STR",
    },
    {
        Name = "恶魔·究极猎手·尤迪安",
        Ubertip = "孤就是黑暗本身，唯吾独尊",
        unitSound = "EvilIllidan",
        file = "war3mapImported\\unit_IllidanEvilflying.mdl",
        Art = "war3mapImported\\icon_unit_Demon.blp",
        modelScale = 1.70,
        scale = 2.40,
        movetp = "hover",
        moveHeight = 75.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_animeslashfinal.mdl",
        cool1 = 1.65,
        Primary = "AGI",
    },
    {
        Name = "恶魔·深渊魔王·麦哥瑟里登",
        Ubertip = "凶暴的外表足以恐吓敌人令他们闻风丧胆",
        unitSound = "DarkRanger",
        file = "units\\demon\\HeroPitLord\\HeroPitLord",
        Art = "ReplaceableTextures\\CommandButtons\\BTNPitLord.blp",
        modelScale = 1.40,
        scale = 2.60,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Voidbolt_Rough_Medium.mdl",
        cool1 = 2.15,
        Primary = "STR",
    },
    {
        Name = "熊猫·酒仙",
        Ubertip = "今朝与酒今朝醉，z～z～Z～～",
        unitSound = "PandarenBrewmaster",
        file = "Units\\Creeps\\PandarenBrewmaster\\PandarenBrewmaster",
        Art = "ReplaceableTextures\\CommandButtons\\BTNPandarenBrewmaster.blp",
        modelScale = 1.70,
        scale = 2.60,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Spells\\Other\\StrongDrink\\BrewmasterMissile.mdl",
        cool1 = 1.85,
        Primary = "STR",
    },
    {
        Name = "熊猫·滚滚",
        Ubertip = "大地手上的石头，据说有上吨重",
        unitSound = "EarthPandarenBrewmaster",
        file = "Units\\Creeps\\EarthPandarenBrewmaster\\EarthPandarenBrewmaster",
        Art = "ReplaceableTextures\\CommandButtons\\BTNEarthBrewmaster.blp",
        modelScale = 1.80,
        scale = 2.40,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\AncientProtectorMissile\\AncientProtectorMissile.mdl",
        cool1 = 2.20,
        Primary = "STR",
    },
    {
        Name = "熊猫·霹雳",
        Ubertip = "嘿～雷电的化身，霹雳来啦",
        abilList = "Alit",
        unitSound = "StormPandarenBrewmaster",
        file = "Units\\Creeps\\StormPandarenBrewmaster\\StormPandarenBrewmaster",
        Art = "ReplaceableTextures\\CommandButtons\\BTNStormBrewmaster.blp",
        modelScale = 1.80,
        scale = 2.40,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FarseerMissile\\FarseerMissile.mdl",
        cool1 = 1.90,
        Primary = "INT",
    },
    {
        Name = "熊猫·无双",
        Ubertip = "双股剑带着身上的余烬，天下无双",
        unitSound = "FirePandarenBrewmaster",
        file = "Units\\Creeps\\FirePandarenBrewmaster\\FirePandarenBrewmaster",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFireBrewmaster.blp",
        modelScale = 1.90,
        scale = 2.70,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Firebolt_Minor.mdl",
        cool1 = 2.00,
        Primary = "AGI",
    },
    {
        Name = "恶魔·灭地·格朗",
        Ubertip = "灾难之主的右护法，沉默寡言，手中杖燃烧着代表大地的紫色火焰",
        unitSound = "",
        file = "war3mapImported\\unit_Aethas.mdl",
        Art = "war3mapImported\\icon_unit_Hunter_Harass.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_violet_arrow.mdl",
        cool1 = 2.00,
        Primary = "INT",
    },
    {
        Name = "恶魔·焚天·罗明",
        Ubertip = "灾难之主的左护法，沉默寡言，手中杖燃烧着代表天空的赤色火焰",
        unitSound = "",
        file = "war3mapImported\\unit_Rhonin.mdl",
        Art = "war3mapImported\\icon_unit_Shadow_ShadowandFlame.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Firebolt_Rough_Minor.mdl",
        cool1 = 2.00,
        Primary = "INT",
    },
    {
        Name = "龙人·青蓝巨兽·凯",
        Ubertip = "超级罕见的龙人族，将冰炼成火焰，异常神奇",
        unitSound = "DoomGuard",
        file = "war3mapImported\\unit_AzureDragonCrystalLord.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNNagaMyrmidon.blp",
        modelScale = 1.50,
        scale = 2.50,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_forst_arrow.mdl",
        cool1 = 1.90,
        Primary = "STR",
    },
    {
        Name = "龙人·炼气大师·李",
        Ubertip = "超级罕见的龙人族，通过将龙魂化作冰焰注入招式，施展奇特的攻击",
        unitSound = "Owlbear",
        file = "war3mapImported\\unit_AzureDragonJudicator.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSnapDragon.blp",
        modelScale = 1.60,
        scale = 2.50,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\FrostWyrmMissile\\FrostWyrmMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
    },
    {
        Name = "人类·绘彩笔仙·素素",
        Ubertip = "素素来自天府国，是帝国的贵宾",
        unitSound = "Runner",
        file = "war3mapImported\\unit_Apheraz_Lucent_Lady_Hive.mdl",
        Art = "war3mapImported\\icon_unit_Elf_Goddess.blp",
        modelScale = 1.80,
        scale = 2.40,
        movetp = "hover",
        moveHeight = 30,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Dustshot.mdl",
        cool1 = 2.10,
        Primary = "INT",
    },
    {
        Name = "巨魔·剑圣·噬魂",
        Ubertip = "死亡的灵魂不会消失，它们会成为我的剑魂",
        unitSound = "Wolfrider",
        file = "war3mapImported\\unit_BladeMasterJungleTrollV1.01.mdl",
        Art = "war3mapImported\\icon_unit_Voljin3.blp",
        modelScale = 1.70,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Culling_Cleave_Silver.mdl",
        cool1 = 1.90,
        Primary = "INT",
    },
    {
        Name = "恶魔·地狱魔爪·维尔",
        Ubertip = "地狱的使者，巨大又可怕的利爪鹿角就是他的特征",
        unitSound = "HeroDemonHunterMorphhed",
        file = "war3mapImported\\unit_Cenarius_Nightmare.mdl",
        Art = "war3mapImported\\icon_unit_FireTempleKeeper.blp",
        modelScale = 1.50,
        scale = 2.60,
        movetp = "horse",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_DarknessBomb.mdl",
        cool1 = 2.10,
        Primary = "AGI",
    },
    {
        Name = "恶魔·毁灭之神·撒旦",
        Ubertip = "剑由毁天之恶魔而生，手由灭世之怨而造",
        unitSound = "",
        file = "war3mapImported\\unit_Nightmare.mdl",
        Art = "war3mapImported\\icon_unit_DemonSpaceShip.blp",
        modelScale = 1.80,
        scale = 2.40,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Voidball_Major.mdl",
        cool1 = 1.50,
        Primary = "AGI",
    },
    {
        Name = "地精·能面鬼·卜",
        Ubertip = "极具战斗力的卜，戴着骨头面具，甚是吓人",
        unitSound = "Kobold",
        file = "war3mapImported\\unit_eligoropt.mdl",
        Art = "war3mapImported\\icon_unit_Eligor.blp",
        modelScale = 1.50,
        scale = 2.35,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_OrbOfCorruption.mdl",
        cool1 = 1.90,
        Primary = "STR",
    },
    {
        Name = "暗夜精灵·丛林守卫者·小鹿",
        Ubertip = "大自然的守卫者，小鹿",
        unitSound = "Dryad",
        file = "war3mapImported\\unit_FlowerDryad.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNDryad.blp",
        modelScale = 1.60,
        scale = 2.10,
        movetp = "horse",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_BlessingArrowMissile.mdl",
        cool1 = 2.00,
        Primary = "AGI",
    },
    {
        Name = "矮人·熊骑士·穆拉丁",
        Ubertip = "听话白熊！我们战无不胜",
        unitSound = "Muradin",
        file = "war3mapImported\\unit_Hero_Dwarven_Rider.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFrostBear.blp",
        modelScale = 1.90,
        scale = 2.50,
        movetp = "horse",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Heart_of_the_Storm_Missile5.mdl",
        cool1 = 2.20,
        Primary = "STR",
    },
    {
        Name = "亡灵·死神·歹",
        Ubertip = "冥冥中自有定数",
        unitSound = "Shade",
        file = "war3mapImported\\unit_Hero_Shinigami.mdl",
        Art = "war3mapImported\\icon_unit_Shadow_Hunter.blp",
        modelScale = 1.10,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_swing_knife.mdl",
        cool1 = 2.20,
        Primary = "AGI",
    },
    {
        Name = "亡灵·冥魂大帝·钢克",
        Ubertip = "冥冥中自有主宰",
        unitSound = "Dreanei",
        file = "war3mapImported\\unit_Skeleton_Death_Knight.mdl",
        Art = "war3mapImported\\icon_unit_Skeletal_Death_Knight_Hero.blp",
        modelScale = 1.50,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_LifeWave.mdl",
        cool1 = 2.20,
        Primary = "STR",
    },
    {
        Name = "昆虫·皮皮虾·皮",
        Ubertip = "是虾，很皮，很开心",
        unitSound = "Lobstrokk",
        file = "war3mapImported\\unit_HeroMakruraMurksnapper.mdl",
        Art = "war3mapImported\\icon_unit_Murksnapper.blp",
        modelScale = 1.30,
        scale = 2.60,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Piercing_Thrust_Purple.mdl",
        cool1 = 2.10,
        Primary = "AGI",
    },
    {
        Name = "娜迦·深红守卫·棘龙",
        Ubertip = "一身赤血，棘龙，攻守兼备，所向无敌",
        unitSound = "DragonSpawn",
        file = "war3mapImported\\unit_HeroNagaStealthViper.mdl",
        Art = "war3mapImported\\icon_unit_Hunter_Pet_CoreHound.blp",
        modelScale = 1.70,
        scale = 2.20,
        movetp = "amph",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_FireBolt_Rough_Medium.mdl",
        cool1 = 2.10,
        Primary = "STR",
    },
    {
        Name = "娜迦·绀青皇冠·塞壬",
        Ubertip = "娜迦族的公主，表面上喜欢二哥波塞冬",
        unitSound = "NagaSiren",
        file = "war3mapImported\\unit_HeroNagaEnchantress.mdl",
        Art = "war3mapImported\\icon_unit_Enchantress.blp",
        modelScale = 1.70,
        scale = 2.20,
        movetp = "amph",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Spirit_Orb.mdl",
        cool1 = 2.00,
        Primary = "INT",
    },
    {
        Name = "娜迦·曳蓝王冠·哈迪斯",
        Ubertip = "娜迦族的第一王子，速度是海妖中最快的，喜爱妹妹塞壬",
        unitSound = "NagaMyrmidon",
        file = "war3mapImported\\unit_NagaDeathKnightFxd.mdl",
        Art = "war3mapImported\\icon_unit_FireDragonElemental.blp",
        modelScale = 1.70,
        scale = 2.20,
        movetp = "amph",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_WaterHands.mdl",
        cool1 = 1.80,
        Primary = "AGI",
    },
    {
        Name = "娜迦·曳蓝王冠·波塞冬",
        Ubertip = "娜迦族的第二王子，速度是海妖中最快的，喜爱妹妹塞壬",
        unitSound = "NagaRoyalGuard",
        file = "war3mapImported\\unit_NagaRoyalGuard_V2.mdl",
        Art = "war3mapImported\\icon_unit_Hunter_Pet_Ravager.blp",
        modelScale = 1.70,
        scale = 2.20,
        movetp = "amph",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_FireBoltMissile.mdl",
        cool1 = 1.80,
        Primary = "STR",
    },
    {
        Name = "娜迦·驱逐者·潮汐巨人",
        Ubertip = "由于对公主无礼而被哈迪斯驱逐出境",
        unitSound = "SeaGiant",
        file = "war3mapImported\\unit_SeaGiantRed.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSeaGiantGreen.blp",
        modelScale = 1.10,
        scale = 2.20,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_fire_tail.mdl",
        cool1 = 1.90,
        Primary = "STR",
    },
    {
        Name = "昆虫·隐术蜘蛛·库莫",
        Ubertip = "潜伏在阴森处的可怕对手，小心它那不能轻松脱离的网术",
        unitSound = "Spider",
        file = "war3mapImported\\unit_HeroNerubianElder.mdl",
        Art = "war3mapImported\\icon_unit_Rogue_StayofExecution.blp",
        modelScale = 1.30,
        scale = 2.60,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_GaussGun.mdl",
        cool1 = 2.10,
        Primary = "AGI",
    },
    {
        Name = "兽人·狮王拳·布布鲁",
        Ubertip = "巨大双拳！开天辟地，震动！震动",
        unitSound = "Wendigo",
        file = "war3mapImported\\unit_HeroSanguineWarlord.mdl",
        Art = "war3mapImported\\icon_unit_Old_Man_Infantry.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_BlackDragonMissile.mdl",
        cool1 = 2.20,
        Primary = "STR",
    },
    {
        Name = "恶魔·鸟面人·伯迪",
        Ubertip = "如果一枪敌人没有死，那就认真地再补一枪",
        unitSound = "GryphonRider",
        file = "war3mapImported\\unit_HeroVialHeart.mdl",
        Art = "war3mapImported\\icon_unit_VialHeart.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_PoisonSpit.mdl",
        cool1 = 2.00,
        Primary = "INT",
    },
    {
        Name = "巨魔·狂魂骑手·阿拉烈",
        Ubertip = "狂魂猎手获得暴龙坐骑更加凶猛可怕",
        unitSound = "HeadHunter",
        file = "war3mapImported\\unit_HeroWarchiefVoljinGlowyEyes.mdl",
        Art = "war3mapImported\\icon_unit_HeroVoljin.blp",
        modelScale = 1.70,
        scale = 2.00,
        movetp = "horse",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_WarchiefMissile.mdl",
        cool1 = 2.10,
        Primary = "AGI",
    },
    {
        Name = "巨魔·狂战士·牙狼",
        Ubertip = "没人知道牙狼的名字，只知道他凶猛无比的那双利爪",
        unitSound = "HeroHunter",
        file = "war3mapImported\\unit_HeroWarder.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHeadhunter.blp",
        modelScale = 2.20,
        scale = 2.50,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Ember_Shield_II_FX_3.mdl",
        cool1 = 1.90,
        Primary = "STR",
    },
    {
        Name = "牛头人·小牛·弹弹",
        Ubertip = "充满活力的弹弹小牛，深受酋长喜爱并重用",
        unitSound = "Tauren",
        file = "war3mapImported\\unit_Hero_TaurenChieftain.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNTauren.blp",
        modelScale = 1.80,
        scale = 2.40,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Dustshot.mdl",
        cool1 = 2.00,
        Primary = "AGI",
    },
    {
        Name = "亡灵·墓坟孤王·嬴",
        Ubertip = "据说此亡灵从秦代皇坟出现，手上是上古名剑，黑鬼双煞",
        unitSound = "Skeleton",
        file = "war3mapImported\\unit_Skeleton_Lord.mdl",
        Art = "war3mapImported\\icon_unit_Bone_Warrior.blp",
        modelScale = 2.00,
        scale = 1.90,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_NimbusBlade.mdl",
        cool1 = 2.00,
        Primary = "STR",
    },
    {
        Name = "矮人·剑圣·极乐",
        Ubertip = "人称极乐老人，剑技非常人能及，超凡入圣",
        unitSound = "Gyrocopter",
        file = "war3mapImported\\unit_UjimasaHojoV1.07.mdl",
        Art = "war3mapImported\\icon_unit_Bone_Helmet.blp",
        modelScale = 2.00,
        scale = 2.00,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_IceboundSting.mdl",
        cool1 = 1.90,
        Primary = "AGI",
    },
    {
        Name = "食人魔·神侍奉·阿尔法",
        Ubertip = "神赐予了唯一的食人魔阿尔法洁白之衣",
        unitSound = "Dreanei",
        file = "war3mapImported\\unit_VindicatorLostOneV1.02.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNDranai.blp",
        modelScale = 1.90,
        scale = 2.10,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_ice_cone_arrow.mdl",
        cool1 = 2.10,
        Primary = "STR",
    },
    {
        Name = "元素·幽鬼灯妖",
        Ubertip = "一直被封印在魔灯之中，直到三千年后才被解救出来，原来为途人实现梦想，现在只想着报复社会",
        unitSound = "FacelessOne",
        file = "war3mapImported\\unit_VoidLord.mdl",
        Art = "war3mapImported\\icon_unit_Evil_God.blp",
        modelScale = 1.40,
        scale = 2.40,
        movetp = "hover",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_DeathMissile.mdl",
        cool1 = 2.00,
        Primary = "INT",
    },
    {
        Name = "元素·虚空谜团",
        Ubertip = "宇宙神秘力量混沌而成，异常诡秘的黑色元素",
        unitSound = "WaterElemental",
        file = "war3mapImported\\unit_VoidWalker.mdl",
        Art = "war3mapImported\\icon_unit_Evil_Spirit.blp",
        modelScale = 1.80,
        scale = 2.40,
        movetp = "hover",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\SpiritOfVengeanceMissile\\SpiritOfVengeanceMissile.mdl",
        cool1 = 2.00,
        Primary = "INT",
    },
    {
        Name = "元素·异性毒虫",
        Ubertip = "次宇宙出现的一种怪虫，含有剧毒",
        unitSound = "NetherDragon",
        file = "war3mapImported\\unit_PoisonElemental.mdl",
        Art = "war3mapImported\\icon_unit_PoisonElemental.blp",
        modelScale = 1.40,
        scale = 2.40,
        movetp = "foot",
        moveHeight = 0,
        weapTp1 = "missile",
        Missileart = "Abilities\\Weapons\\ChimaeraAcidMissile\\ChimaeraAcidMissile.mdl",
        cool1 = 2.00,
        Primary = "INT",
    },
    {
        Name = "亡灵·勾魂使者·戴泽",
        Ubertip = "它，前世死了之后,在冥界做灵魂回收员",
        unitSound = "Ghost",
        file = "war3mapImported\\unit_wraith_final.mdl",
        Art = "war3mapImported\\icon_unit_Wraith2.blp",
        modelScale = 1.80,
        scale = 2.00,
        movetp = "hover",
        moveHeight = 10.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_NewSoulArmor.mdl",
        cool1 = 2.10,
        Primary = "STR",
    },
    {
        Name = "异兽·猴王·悟空",
        Ubertip = "从远古天产灵石中孕育风化之石猴，身俱天地灵气日月精华，系花果山美猴王",
        unitSound = "Owlbear",
        file = "war3mapImported\\unit_MonkeyKing.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGrizzlyBear.blp",
        modelScale = 1.90,
        scale = 2.10,
        movetp = "foot",
        moveHeight = 0.00,
        weapTp1 = "missile",
        Missileart = "war3mapImported\\eff_Culling_Cleave_Purple.mdl",
        cool1 = 1.90,
        Primary = "AGI",
    },
}
