--锤子一个
local aobj = slk.ability.AHtb:new("defeat_human")
local Name = "有爱的锤子"
aobj.Name = Name
aobj.Tip = "锤他！就是他(" .. hColor.yellow("Q") .. ")"
aobj.Hotkey = "Q"
aobj.Ubertip = "虽然你败了，依然可以控制逃走的小兵锤剩下的可恶的玩家|n看谁不爽就锤他！|n" .. hColor.yellow("锤子造成眩晕3秒")
aobj.Buttonpos1 = 0
aobj.Buttonpos2 = 2
aobj.hero = 0
aobj.levels = 1
aobj.DataA1 = 0.01
aobj.Cool1 = 9
aobj.Dur1 = 3
aobj.HeroDur1 = 3
aobj.Cost1 = 0
aobj.targs1 = "neutral,vulnerable,ground,enemies,invulnerable,organic,debris,air,friend,self"
aobj.EffectArt = ""
aobj.TargetArt = ""
local abid = aobj:get_id()

local obj = slk.unit.ogru:new("couriers_defeat")
obj.Name = "[信使]不服输锤子兵"
obj.type = "Peon"
obj.upgrades = ""
obj.weapsOn = 0
obj.Hotkey = ""
obj.tilesets = 1
obj.hostilePal = 0
obj.Requires = ""
obj.Requirescount = 1
obj.Requires1 = ""
obj.Requires2 = ""
obj.upgrade = ""
obj.collision = 0.00
obj.unitShadow = "ShadowFlyer"
obj.Buttonpos1 = 0
obj.Buttonpos2 = 0
obj.death = 0.10
obj.turnRate = 1.00
obj.acquire = 1000.00
obj.race = "human"
obj.deathType = 0
obj.fused = 0
obj.sides1 = 5 --骰子面
obj.dice1 = 1 --骰子数量
obj.regenMana = 0.00
obj.HP = 99999
obj.regenHP = 99999
obj.stockStart = 0
obj.stockRegen = 0
obj.stockMax = 1
obj.collision = 0
obj.def = 0
obj.sight = 1000
obj.nsight = 1000
obj.Ubertip = "神勇敢死队"
obj.unitSound = "Draenei"
obj.modelScale = 1.00
obj.file = "units\\other\\DranaiMage\\DranaiMage"
obj.Art = "ReplaceableTextures\\CommandButtons\\BTNDranaiMage.blp"
obj.scale = 1.00
obj.movetp = "foot"
obj.moveHeight = 0
obj.moveFloor = 0
obj.spd = 400
obj.targType = "air"
obj.upgrades = ""
obj.Builds = ""
obj.fused = 0
obj.abilList = "Avul," .. abid
?>
call SaveInteger(hash_myslk, StringHash("couriers_defeat"), 0, '<?=obj:get_id()?>')
<?
