-- 测试的3秒 代码
-- htime.setInterval(
--     5.00,
--     function()
--         print("-a" .. table.len(hRuntime.attribute))
--         print("-" .. table.len(hRuntime.attributeDiff))
--         print("-" .. table.len(hRuntime.unit))
--         print("-e" .. table.len(hRuntime.event))
--     end
-- )
