items_fun = {
    {
        Name = "天剑切符",
        Description = "呼唤奇剑降临！",
        goldcost = 5000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_TarotGreatness.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令您的兵塔队伍获得神攻击特性并且攻击力提升500|n持续30秒",
        cooldown = 25,
        I_TYPE = "strategy"
    },
    {
        Name = "武神切符",
        Description = "呼唤神勇降临！",
        goldcost = 5000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_TarotBerserker.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令您的兵塔队伍获得攻击速度提升75%|n持续30秒",
        cooldown = 25,
        I_TYPE = "strategy"
    },
    {
        Name = "变异切符",
        Description = "进化在于变异",
        goldcost = 5000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_TarotChaos.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令您的兵塔队伍获得火、水、冰、风、雷、土6种攻击特性|n持续30秒",
        cooldown = 25,
        I_TYPE = "strategy"
    },
    {
        Name = "恶魔切符",
        Description = "呼唤恶魔！来吧！",
        goldcost = 5000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_TarotDeath.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令您的兵塔队伍伤害增幅提升33%，但护甲减少100点|n持续30秒",
        cooldown = 25,
        I_TYPE = "strategy"
    },
    {
        Name = "恶灵切符",
        Description = "呼唤恶鬼降临！",
        goldcost = 5000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_TarotUndeath.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令您的兵塔队伍提升50%鬼攻击|n持续30秒",
        cooldown = 20,
        I_TYPE = "strategy"
    },
    {
        Name = "圣杯切符",
        Description = "这里没有圣剑~",
        goldcost = 5000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_TarotIllusion.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令您的黄金获得率提升15%|n持续90秒",
        cooldown = 20,
        I_TYPE = "strategy"
    },
    {
        Name = "陋室切符",
        Description = "斯是陋室，惟吾德馨",
        goldcost = 5000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_TarotPrism.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令您的兵塔经验率提升20%|n持续90秒",
        cooldown = 20,
        I_TYPE = "strategy"
    },
    {
        Name = "王室切符",
        Description = "Ready to work~",
        goldcost = 5000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_TarotLords.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令您黄金获得率提升10%，并且售卖时提升25%回本|n持续90秒",
        cooldown = 20,
        I_TYPE = "strategy"
    },
    {
        Name = "锤敕令",
        Description = "号召巨锤袭击",
        goldcost = 80000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_WeaponScroll01",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令其他玩家的所有塔眩晕10秒",
        cooldown = 25,
        I_TYPE = "strategy"
    },
    {
        Name = "盾敕令",
        Description = "号召大剑袭击",
        goldcost = 80000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_ArmorScroll02.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令其他玩家的所有塔攻速减少100%持续10秒",
        cooldown = 25,
        I_TYPE = "strategy"
    },
    {
        Name = "剑敕令",
        Description = "号召大剑袭击",
        goldcost = 80000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_WeaponScroll03.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令其他玩家的信使眩晕10秒",
        cooldown = 25,
        I_TYPE = "strategy"
    },
    {
        Name = "斧敕令",
        Description = "号召猛斧袭击",
        goldcost = 80000,
        lumbercost = 0,
        Art = "war3mapImported\\icon_item_Inscription_WeaponScroll02.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        ACTIVE = "令其他玩家的主兵塔生命瞬间减少当前的20%",
        cooldown = 25,
        I_TYPE = "strategy"
    }
}
