abilities = {
    {
        Name = "致命一击",
        ABILITY_COLOR = "red",
        Art = "ReplaceableTextures\\PassiveButtons\\PASBTNCriticalStrike.blp",
        Ubertip = "增加物理暴击几率{val#1}%，增加物理暴击伤害50%",
        Val = { 10 },
        WEIGHT = 0.01,
        OVERLIE = 99,
    },
    {
        Name = "致命爆击",
        ABILITY_COLOR = "red",
        Art = "ReplaceableTextures\\PassiveButtons\\PASBTNCriticalStrike.blp",
        Ubertip = "增加物理暴击几率{val#1}%，增加物理暴击伤害{val#2}%",
        Val = { 5, 10 },
        WEIGHT = 0.01,
        OVERLIE = 99,
    },
    {
        Name = "魔法回应",
        ABILITY_COLOR = "red",
        Art = "ReplaceableTextures\\PassiveButtons\\PASBTNFeedBack.blp",
        Ubertip = "增加魔法暴击几率{val#1}%，增加魔法暴击伤害50%",
        Val = { 10 },
        WEIGHT = 0.01,
        OVERLIE = 99,
    },
    {
        Name = "魔法回爆",
        ABILITY_COLOR = "red",
        Art = "ReplaceableTextures\\PassiveButtons\\PASBTNFeedBack.blp",
        Ubertip = "增加魔法暴击几率{val#1}%，增加魔法暴击伤害{val#2}%",
        Val = { 5, 10 },
        WEIGHT = 0.01,
        OVERLIE = 99,
    },
    {
        Name = "剑气",
        ABILITY_COLOR = "yellow",
        Art = "ReplaceableTextures\\PassiveButtons\\PASBTNCommand.blp",
        Ubertip = "有10%几率发出一道距离800剑气，令一条直线的敌人受到{val#1}点伤害",
        Val = { 175 },
        WEIGHT = 0.01,
        OVERLIE = 99,
    }
}