couriers = {
    {
        Name = "呆萌的青蛙",
        unitSound = "Frog",
        file = "units\\critters\\Frog\\Frog",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHex.blp",
        modelScale = 1.50,
        scale = 1.20,
        moveHeight = 0,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 1
    },
    {
        Name = "冷静的绵羊",
        unitSound = "Sheep",
        file = "units\\critters\\Sheep\\Sheep",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSheep.blp",
        modelScale = 1.50,
        scale = 1.20,
        moveHeight = 0,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 15
    },
    {
        Name = "小饥鸡",
        unitSound = "Chicken",
        file = "units\\critters\\EasterChicken\\EasterChicken",
        Art = "ReplaceableTextures\\CommandButtons\\BTNCritterChicken.blp",
        modelScale = 1.40,
        scale = 1.20,
        moveHeight = 0,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 20
    },
    {
        Name = "依诺吸吸",
        unitSound = "QuillBeast",
        file = "units\\critters\\Felboar\\Felboar",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFelBoar.blp",
        modelScale = 1.40,
        scale = 1.20,
        moveHeight = 0,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 25
    },
    {
        Name = "灵动的雪鹰",
        unitSound = "SnowOwl",
        file = "units\\critters\\SnowOwl\\SnowOwl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSnowOwl.blp",
        modelScale = 1.20,
        scale = 1.20,
        movetp = "fly",
        moveHeight = 225.00,
        spd = 450,
        targType = "air",
        armor = "Flesh",
        lumbercost = 30
    },
    {
        Name = "涅磐火凤凰",
        unitSound = "Phoenix",
        file = "units\\human\\phoenix\\phoenix",
        Art = "war3mapImported\\icon_unit_Phoenix.blp",
        modelScale = 1.20,
        scale = 1.10,
        movetp = "fly",
        moveHeight = 250.00,
        spd = 500,
        targType = "air",
        armor = "Ethereal",
        lumbercost = 0
    },
    {
        Name = "冰戟剑灵",
        unitSound = "Gargoyle",
        file = "war3mapImported\\unit_Frost_Fury_v1.1.mdl",
        Art = "war3mapImported\\icon_unit_Hunter_Pet_Moth.blp",
        modelScale = 1.50,
        scale = 1.30,
        movetp = "fly",
        moveHeight = 200.00,
        spd = 522,
        targType = "air",
        armor = "Ethereal",
        lumbercost = 0
    }
}
