
couriers = {
    {
        Name = "呆萌的青蛙",
        abilList = "Avul,AInv",
        unitSound = "Frog",
        file = "units\\critters\\Frog\\Frog",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHex.blp",
        modelScale = 1.50,
        scale = 1.20,
        movetp = "foot",
        moveHeight = 0,
        spd = 270,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 25,
        COURIER_POWER = "E",
    },
    {
        Name = "V5的螃蟹",
        abilList = "Avul,AInv",
        unitSound = "Frog",
        file = "units\\critters\\SpiderCrab\\SpiderCrab",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSpiderCrab.blp",
        modelScale = 1.40,
        scale = 1.20,
        movetp = "foot",
        moveHeight = 0,
        spd = 275,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 50,
        COURIER_POWER = "E",
    },
    {
        Name = "友爱的海豹",
        abilList = "Avul,AInv",
        unitSound = "Seal",
        file = "units\\critters\\Seal\\Seal",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSeal.blp",
        modelScale = 1.30,
        scale = 1.20,
        movetp = "foot",
        moveHeight = 0,
        spd = 275,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 50,
        COURIER_POWER = "E",
    },
    {
        Name = "狡猾的浣熊",
        abilList = "Avul,AInv",
        unitSound = "Raccoon",
        file = "units\\critters\\Raccoon\\Raccoon",
        Art = "ReplaceableTextures\\CommandButtons\\BTNRacoon.blp",
        modelScale = 1.30,
        scale = 1.20,
        movetp = "foot",
        moveHeight = 0,
        spd = 300,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 75,
        COURIER_POWER = "E",
    },
    {
        Name = "冷静的绵羊",
        abilList = "Avul,AInv",
        unitSound = "Sheep",
        file = "units\\critters\\Sheep\\Sheep",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSheep.blp",
        modelScale = 1.50,
        scale = 1.20,
        movetp = "foot",
        moveHeight = 0,
        spd = 350,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 100,
        COURIER_POWER = "D",
    },
    {
        Name = "卡呐诺企鹅",
        abilList = "Avul,AInv",
        unitSound = "Penguin",
        file = "units\\critters\\Penguin\\Penguin",
        Art = "ReplaceableTextures\\CommandButtons\\BTNPenguin.blp",
        modelScale = 1.50,
        scale = 1.20,
        movetp = "foot",
        moveHeight = 0,
        spd = 350,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 100,
        COURIER_POWER = "D",
    },
    {
        Name = "兔子兔子",
        abilList = "Avul,AInv",
        unitSound = "Rabbit",
        file = "units\\critters\\EasterRabbit\\EasterRabbit",
        Art = "ReplaceableTextures\\CommandButtons\\BTNCritterRabbit.blp",
        modelScale = 1.50,
        scale = 1.20,
        movetp = "foot",
        moveHeight = 0,
        spd = 375,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 150,
        COURIER_POWER = "C",
    },
    {
        Name = "小饥鸡",
        abilList = "Avul,AInv",
        unitSound = "Chicken",
        file = "units\\critters\\EasterChicken\\EasterChicken",
        Art = "ReplaceableTextures\\CommandButtons\\BTNCritterChicken.blp",
        modelScale = 1.40,
        scale = 1.20,
        movetp = "foot",
        moveHeight = 0,
        spd = 375,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 150,
        COURIER_POWER = "C",
    },
    {
        Name = "宁静麋鹿",
        abilList = "Avul,AInv",
        unitSound = "",
        file = "units\\critters\\BlackStagMale\\BlackStagMale",
        Art = "ReplaceableTextures\\CommandButtons\\BTNStag.blp",
        modelScale = 1.50,
        scale = 1.20,
        movetp = "foot",
        moveHeight = 0,
        spd = 400,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 200,
        COURIER_POWER = "B",
    },
    {
        Name = "依诺吸吸",
        abilList = "Avul,AInv",
        unitSound = "QuillBeast",
        file = "units\\critters\\Felboar\\Felboar",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFelBoar.blp",
        modelScale = 1.40,
        scale = 1.20,
        movetp = "foot",
        moveHeight = 0,
        spd = 400,
        targType = "ground",
        armor = "Flesh",
        lumbercost = 200,
        COURIER_POWER = "B",
    },
    {
        Name = "灵动的雪鹰",
        abilList = "Avul,AInv",
        unitSound = "SnowOwl",
        file = "units\\critters\\SnowOwl\\SnowOwl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSnowOwl.blp",
        modelScale = 1.20,
        scale = 1.20,
        movetp = "fly",
        moveHeight = 225.00,
        spd = 450,
        targType = "air",
        armor = "Flesh",
        lumbercost = 250,
        COURIER_POWER = "A",
    },
    {
        Name = "信天！翁",
        abilList = "Avul,AInv",
        unitSound = "Albatross",
        file = "units\\critters\\Albatross\\Albatross",
        Art = "ReplaceableTextures\\CommandButtons\\BTNAlbatross.blp",
        modelScale = 1.30,
        scale = 1.20,
        movetp = "fly",
        moveHeight = 225.00,
        spd = 475,
        targType = "air",
        armor = "Flesh",
        lumbercost = 300,
        COURIER_POWER = "S",
    },
    {
        Name = "涅磐火凤凰",
        abilList = "Avul,AInv",
        unitSound = "Phoenix",
        file = "units\\human\\phoenix\\phoenix",
        Art = "war3mapImported\\icon_unit_Phoenix.blp",
        modelScale = 1.20,
        scale = 1.10,
        movetp = "fly",
        moveHeight = 250.00,
        spd = 500,
        targType = "air",
        armor = "Ethereal",
        lumbercost = 0,
        COURIER_POWER = "SS",
    },
    {
        Name = "幻想灵体",
        abilList = "Avul,AInv",
        unitSound = "",
        file = "units\\human\\phoenix\\phoenix",
        Art = "ReplaceableTextures\\CommandButtons\\BTNMarkOfFire.blp",
        modelScale = 1.20,
        scale = 1.10,
        movetp = "fly",
        moveHeight = 250.00,
        spd = 522,
        targType = "air",
        armor = "Ethereal",
        lumbercost = 0,
        COURIER_POWER = "SSS",
    },
}