enemysBoss = {
    {
        Name = "陨石火",
        file = "war3mapImported\\unit_abyssal_illidan.mdx",
        modelScale = 2.00,
        scale = 2.50,
    },
    {
        Name = "异动机车",
        file = "war3mapImported\\unit_Aestus.mdx",
        modelScale = 2.00,
        scale = 2.50,
    },
    {
        Name = "大气之灵",
        file = "war3mapImported\\unit_air.mdx",
        modelScale = 1.90,
        scale = 2.50,
    },
    {
        Name = "风暴之灵",
        file = "war3mapImported\\unit_AirElemental.mdx",
        modelScale = 2.60,
        scale = 2.50,
    },
    {
        Name = "钻石巨人",
        file = "war3mapImported\\unit_AncientOfStone(heavy).mdx",
        modelScale = 1.80,
        scale = 2.50,
    },
    {
        Name = "排骨之刃",
        file = "war3mapImported\\unit_Banisher.mdx",
        modelScale = 2.00,
        scale = 2.50,
    },
    {
        Name = "金属火",
        file = "war3mapImported\\unit_BrassInfernal.mdx",
        modelScale = 1.70,
        scale = 2.50,
    },
    {
        Name = "两级行刑人",
        file = "war3mapImported\\unit_Celsius.mdx",
        modelScale = 2.30,
        scale = 2.50,
    },
    {
        Name = "剧毒蜘蛛",
        file = "war3mapImported\\unit_Dark_Spider.mdx",
        modelScale = 2.20,
        scale = 2.50,
    },
    {
        Name = "幽火之灵",
        file = "war3mapImported\\unit_Dark1.mdx",
        modelScale = 2.70,
        scale = 2.50,
    },
    {
        Name = "剑圣·诡",
        file = "war3mapImported\\unit_DeathKnightOrcV1.01.mdx",
        modelScale = 2.30,
        scale = 2.50,
    },
    {
        Name = "墓场魔神",
        file = "war3mapImported\\unit_EarthLich.mdx",
        modelScale = 2.60,
        scale = 2.50,
    },
    {
        Name = "逗趣火炎蜥",
        file = "war3mapImported\\unit_FireElemental.mdx",
        modelScale = 2.00,
        scale = 2.50,
    },
    {
        Name = "赤焰之灵",
        file = "war3mapImported\\unit_FireElemental2.mdx",
        modelScale = 2.40,
        scale = 2.50,
    },
    {
        Name = "青焰之灵",
        file = "war3mapImported\\unit_FireElementalGreen.mdx",
        modelScale = 2.40,
        scale = 2.50,
    },
    {
        Name = "鬼神小鬼",
        file = "war3mapImported\\unit_Firestarter.mdx",
        modelScale = 2.40,
        scale = 2.50,
    },
    {
        Name = "火焰狱监",
        file = "war3mapImported\\unit_FireTempleKeeperElemental.mdx",
        modelScale = 1.60,
        scale = 2.50,
    },
    {
        Name = "火火火",
        file = "war3mapImported\\unit_FireTitan.mdx",
        modelScale = 1.90,
        scale = 2.50,
    },
    {
        Name = "冰冰冰",
        file = "war3mapImported\\unit_FrostTitan.mdx",
        modelScale = 1.70,
        scale = 2.50,
    },
    {
        Name = "坟场魔神",
        file = "war3mapImported\\unit_IcecrownSeer.mdl",
        modelScale = 2.40,
        scale = 2.50,
    },
    {
        Name = "冰巨人",
        file = "war3mapImported\\unit_iceElemental.mdx",
        modelScale = 1.70,
        scale = 2.50,
    },
    {
        Name = "水晶灰狼",
        file = "war3mapImported\\unit_Icewolf.mdx",
        modelScale = 2.00,
        scale = 2.50,
    },
    {
        Name = "异动机车人",
        file = "war3mapImported\\unit_InfernalWheeledWarrior.mdx",
        modelScale = 2.00,
        scale = 2.50,
    },
    {
        Name = "Jack",
        file = "war3mapImported\\unit_JackONightmare.mdx",
        modelScale = 2.50,
        scale = 2.50,
    },
    {
        Name = "巫妖",
        file = "war3mapImported\\unit_Kelthuzad_Lich.mdx",
        modelScale = 2.30,
        scale = 2.50,
    },
    {
        Name = "岩浆火",
        file = "war3mapImported\\unit_LavaGolemFinalwPortrait.mdx",
        modelScale = 2.00,
        scale = 2.50,
    },
    {
        Name = "闪电结合体",
        file = "war3mapImported\\unit_LightningTitan.mdx",
        modelScale = 1.60,
        scale = 2.50,
    },
    {
        Name = "伊邪那岐",
        file = "war3mapImported\\unit_Mindflayer.mdx",
        modelScale = 2.30,
        scale = 2.50,
    },
    {
        Name = "耍个锤子",
        file = "war3mapImported\\unit_MoargOverlord1.mdx",
        modelScale = 1.60,
        scale = 2.50,
    },
    {
        Name = "熔炉恶魔",
        file = "war3mapImported\\unit_ObsidianGolem.mdx",
        modelScale = 1.60,
        scale = 2.50,
    },
    {
        Name = "火山巨人",
        file = "war3mapImported\\unit_RagnarosMinion.mdx",
        modelScale = 1.80,
        scale = 2.50,
    },
    {
        Name = "滚动岩",
        file = "war3mapImported\\unit_Rock Elemental.mdx",
        modelScale = 2.00,
        scale = 2.50,
    },
    {
        Name = "沙人",
        file = "war3mapImported\\unit_SandElementalV9_Final.mdx",
        modelScale = 2.10,
        scale = 2.50,
    },
    {
        Name = "暗黑巨人",
        file = "war3mapImported\\unit_ShadowInfernal.mdx",
        modelScale = 1.70,
        scale = 2.50,
    },
    {
        Name = "暗黑魔神",
        file = "war3mapImported\\unit_ShadowInfernal2.mdx",
        modelScale = 1.65,
        scale = 2.50,
    },
    {
        Name = "水之领主",
        file = "war3mapImported\\unit_WaterElemental.mdx",
        modelScale = 2.00,
        scale = 2.50,
    },
    {
        Name = "水魔神",
        file = "war3mapImported\\unit_Waterlord.mdx",
        modelScale = 1.60,
        scale = 2.50,
    },
    {
        Name = "风枝虚无",
        file = "war3mapImported\\unit_WindElemental.mdx",
        modelScale = 1.80,
        scale = 2.50,
    },
    {
        Name = "红牙方舟",
        file = "war3mapImported\\unit_DemonSpaceShip.mdx",
        modelScale = 1.30,
        scale = 2.50,
        movetp = "fly",
        moveHeight = 250,
    },
}