enemys = {
    {
        Name = "侍僧",
        file = "units\\undead\\Acolyte\\Acolyte",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Acolyte",
    },
    {
        Name = "鬼影",
        file = "units\\undead\\Shade\\Shade",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Shade",
        movetp = "hover",
        moveHeight = 50,
    },
    {
        Name = "食尸鬼",
        file = "units\\undead\\Ghoul\\Ghoul",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Ghoul",
    },
    {
        Name = "憎恶",
        file = "units\\undead\\Abomination\\Abomination",
        modelScale = 0.90,
        scale = 2.10,
        unitSound = "Abomination",
    },
    {
        Name = "绞肉车",
        file = "units\\undead\\MeatWagon\\MeatWagon",
        modelScale = 0.90,
        scale = 2.40,
        unitSound = "MeatWagon",
    },
    {
        Name = "穴居恶魔",
        file = "units\\undead\\CryptFiend\\CryptFiend",
        modelScale = 0.90,
        scale = 1.90,
        unitSound = "CryptFiend",
    },
    {
        Name = "石像鬼",
        file = "units\\undead\\Gargoyle\\Gargoyle",
        modelScale = 1.00,
        scale = 1.25,
        unitSound = "Gargoyle",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "女妖",
        file = "units\\undead\\Banshee\\Banshee",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Banshee",
        movetp = "hover",
        moveHeight = 50,
    },
    {
        Name = "不死族巫师",
        file = "units\\undead\\Necromancer\\Necromancer",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Necromancer",
    },
    {
        Name = "十胜石雕像",
        file = "units\\undead\\ObsidianStatue\\ObsidianStatue",
        modelScale = 0.80,
        scale = 2.00,
        unitSound = "ObsidianStatue",
    },
    {
        Name = "冰霜巨龙",
        file = "units\\undead\\FrostWyrm\\FrostWyrm",
        modelScale = 0.80,
        scale = 2.00,
        unitSound = "FrostWyrm",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "蝗虫",
        file = "units\\undead\\Locust\\Locust",
        modelScale = 1.20,
        scale = 1.20,
        unitSound = "Locust",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "骷髅战士",
        file = "units\\undead\\Skeleton\\Skeleton",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Skeleton",
    },
    {
        Name = "骷髅魔法师",
        file = "units\\undead\\SkeletonMage\\SkeletonMage",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Skeleton",
    },
    {
        Name = "腐尸甲虫",
        file = "units\\undead\\scarab\\scarab",
        modelScale = 1.20,
        scale = 1.20,
        unitSound = "Scarab",
    },
    {
        Name = "僵尸",
        file = "units\\creeps\\Zombie\\Zombie",
        modelScale = 1.15,
        scale = 1.00,
        unitSound = "Zombie",
    },
    {
        Name = "飞艇",
        file = "units\\undead\\UndeadAirBarge\\UndeadAirBarge",
        modelScale = 1.00,
        scale = 2.00,
        unitSound = "",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "奇美拉",
        file = "units\\nightelf\\Chimaera\\Chimaera",
        modelScale = 1.00,
        scale = 2.00,
        unitSound = "Chimaera",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "囚车",
        file = "units\\other\\IllidanEvilCaged\\IllidanEvilCaged",
        modelScale = 1.00,
        scale = 2.50,
        unitSound = "PrisonWagon",
    },
    {
        Name = "囚车",
        file = "units\\other\\IllidanEvilCaged\\IllidanEvilCaged",
        modelScale = 1.00,
        scale = 2.50,
        unitSound = "PrisonWagon",
    },
    {
        Name = "孤胆怪物",
        file = "units\\other\\DalaranReject\\DalaranReject",
        modelScale = 1.15,
        scale = 1.45,
        unitSound = "Zombie",
    },
    {
        Name = "变种怪物",
        file = "units\\other\\DalaranMutant\\DalaranMutant",
        modelScale = 1.75,
        scale = 1.10,
        unitSound = "Zombie",
    },
    {
        Name = "丛林漫步者",
        file = "units\\creeps\\JungleBeast\\JungleBeast",
        modelScale = 1.00,
        scale = 1.10,
        unitSound = "Wendigo",
    },
    {
        Name = "阿卡那瑟德刺人",
        file = "Units\\Creeps\\Archnathid\\Archnathid",
        modelScale = 0.70,
        scale = 1.40,
        unitSound = "Archnathid",
    },
    {
        Name = "阿卡那瑟德领主",
        file = "Units\\Creeps\\Archnathidpurple\\Archnathidpurple",
        modelScale = 1.10,
        scale = 1.70,
        unitSound = "Archnathid",
    },
    {
        Name = "强盗",
        file = "units\\creeps\\Bandit\\Bandit",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Bandit",
    },
    {
        Name = "土匪",
        file = "units\\creeps\\BanditSpearThrower\\BanditSpearThrower",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Bandit",
    },
}