enemys = {
    {
        Name = "侍僧",
        file = "units\\undead\\Acolyte\\Acolyte",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Acolyte",
    },
    {
        Name = "鬼影",
        file = "units\\undead\\Shade\\Shade",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Shade",
        movetp = "hover",
        moveHeight = 50,
    },
    {
        Name = "食尸鬼",
        file = "units\\undead\\Ghoul\\Ghoul",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Ghoul",
    },
    {
        Name = "憎恶",
        file = "units\\undead\\Abomination\\Abomination",
        modelScale = 0.90,
        scale = 2.10,
        unitSound = "Abomination",
    },
    {
        Name = "绞肉车",
        file = "units\\undead\\MeatWagon\\MeatWagon",
        modelScale = 0.90,
        scale = 2.40,
        unitSound = "MeatWagon",
    },
    {
        Name = "穴居恶魔",
        file = "units\\undead\\CryptFiend\\CryptFiend",
        modelScale = 0.90,
        scale = 1.90,
        unitSound = "CryptFiend",
    },
    {
        Name = "石像鬼",
        file = "units\\undead\\Gargoyle\\Gargoyle",
        modelScale = 1.00,
        scale = 1.25,
        unitSound = "Gargoyle",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "女妖",
        file = "units\\undead\\Banshee\\Banshee",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Banshee",
        movetp = "hover",
        moveHeight = 50,
    },
    {
        Name = "不死族巫师",
        file = "units\\undead\\Necromancer\\Necromancer",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Necromancer",
    },
    {
        Name = "十胜石雕像",
        file = "units\\undead\\ObsidianStatue\\ObsidianStatue",
        modelScale = 0.80,
        scale = 2.00,
        unitSound = "ObsidianStatue",
    },
    {
        Name = "冰霜巨龙",
        file = "units\\undead\\FrostWyrm\\FrostWyrm",
        modelScale = 0.80,
        scale = 2.00,
        unitSound = "FrostWyrm",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "蝗虫",
        file = "units\\undead\\Locust\\Locust",
        modelScale = 1.20,
        scale = 1.20,
        unitSound = "Locust",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "骷髅战士",
        file = "units\\undead\\Skeleton\\Skeleton",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Skeleton",
    },
    {
        Name = "骷髅魔法师",
        file = "units\\undead\\SkeletonMage\\SkeletonMage",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Skeleton",
    },
    {
        Name = "腐尸甲虫",
        file = "units\\undead\\scarab\\scarab",
        modelScale = 1.20,
        scale = 1.20,
        unitSound = "Scarab",
    },
    {
        Name = "僵尸",
        file = "units\\creeps\\Zombie\\Zombie",
        modelScale = 1.15,
        scale = 1.00,
        unitSound = "Zombie",
    },
    {
        Name = "飞艇",
        file = "units\\undead\\UndeadAirBarge\\UndeadAirBarge",
        modelScale = 1.00,
        scale = 2.00,
        unitSound = "",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "奇美拉",
        file = "units\\nightelf\\Chimaera\\Chimaera",
        modelScale = 1.00,
        scale = 2.00,
        unitSound = "Chimaera",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "囚车",
        file = "units\\other\\IllidanEvilCaged\\IllidanEvilCaged",
        modelScale = 1.00,
        scale = 2.50,
        unitSound = "PrisonWagon",
    },
    {
        Name = "囚车",
        file = "units\\other\\IllidanEvilCaged\\IllidanEvilCaged",
        modelScale = 1.00,
        scale = 2.50,
        unitSound = "PrisonWagon",
    },
    {
        Name = "孤胆怪物",
        file = "units\\other\\DalaranReject\\DalaranReject",
        modelScale = 1.15,
        scale = 1.45,
        unitSound = "Zombie",
    },
    {
        Name = "变种怪物",
        file = "units\\other\\DalaranMutant\\DalaranMutant",
        modelScale = 1.75,
        scale = 1.10,
        unitSound = "Zombie",
    },
    {
        Name = "丛林漫步者",
        file = "units\\creeps\\JungleBeast\\JungleBeast",
        modelScale = 1.00,
        scale = 1.10,
        unitSound = "Wendigo",
    },
    {
        Name = "阿卡那瑟德刺人",
        file = "Units\\Creeps\\Archnathid\\Archnathid",
        modelScale = 0.70,
        scale = 1.40,
        unitSound = "Archnathid",
    },
    {
        Name = "阿卡那瑟德领主",
        file = "Units\\Creeps\\Archnathidpurple\\Archnathidpurple",
        modelScale = 1.10,
        scale = 1.70,
        unitSound = "Archnathid",
    },
    {
        Name = "强盗",
        file = "units\\creeps\\Bandit\\Bandit",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Bandit",
    },
    {
        Name = "土匪",
        file = "units\\creeps\\BanditSpearThrower\\BanditSpearThrower",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Bandit",
    },
    {
        Name = "强盗领主",
        file = "units\\creeps\\BanditLord\\BanditLord",
        modelScale = 1.10,
        scale = 1.15,
        unitSound = "Bandit",
    },
    {
        Name = "龙卵盗贼",
        file = "Units\\Creeps\\DragonSpawnBlue\\DragonSpawnBlue",
        modelScale = 0.90,
        scale = 1.70,
        unitSound = "DragonSpawn",
    },
    {
        Name = "龙卵学徒",
        file = "Units\\Creeps\\DragonSpawnGreen\\DragonSpawnGreen",
        modelScale = 0.90,
        scale = 1.70,
        unitSound = "DragonSpawn",
    },
    {
        Name = "龙卵战士",
        file = "Units\\Creeps\\DragonSpawnPurple\\DragonSpawnPurple",
        modelScale = 1.15,
        scale = 2.20,
        unitSound = "DragonSpawn",
    },
    {
        Name = "半人马弓箭手",
        file = "units\\creeps\\CentaurArcher\\CentaurArcher",
        modelScale = 1.00,
        scale = 1.20,
        unitSound = "CentaurArcher",
    },
    {
        Name = "半人马苦工",
        file = "units\\creeps\\Centaur\\Centaur",
        modelScale = 1.10,
        scale = 1.10,
        unitSound = "Centaur",
    },
    {
        Name = "半人马巫师",
        file = "units\\creeps\\CentaurKhan\\CentaurKhan",
        modelScale = 1.20,
        scale = 1.40,
        unitSound = "CentaurArcher",
    },
    {
        Name = "蜘蛛螃蟹",
        file = "units\\creeps\\SpiderCrabCreep\\SpiderCrabCreep",
        modelScale = 1.00,
        scale = 1.20,
        unitSound = "",
    },
    {
        Name = "黑暗巨魔",
        file = "units\\creeps\\DarkTroll\\DarkTroll",
        modelScale = 0.85,
        scale = 1.00,
        unitSound = "ForestTroll",
    },
    {
        Name = "黑魔影子牧师",
        file = "units\\creeps\\DarkTrollShadowPriest\\DarkTrollShadowPriest",
        modelScale = 0.80,
        scale = 1.30,
        unitSound = "ForestTrollShadowPriest",
    },
    {
        Name = "黑魔猎手",
        file = "units\\creeps\\DarkTrollTrapper\\DarkTrollTrapper",
        modelScale = 1.15,
        scale = 1.00,
        unitSound = "ForestTroll",
    },
    {
        Name = "达拉内尔守卫",
        file = "units\\other\\Dranai\\Dranai",
        modelScale = 0.90,
        scale = 1.00,
        unitSound = "Draenei",
    },
    {
        Name = "达拉内尔护卫",
        file = "units\\other\\DranaiWhite\\DranaiWhite",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Draenei",
    },
    {
        Name = "达拉内尔信徒",
        file = "units\\other\\DranaiMage\\DranaiMage",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Draenei",
    },
    {
        Name = "红幼龙",
        file = "units\\creeps\\RedDragonWelp\\RedDragonWelp",
        modelScale = 0.65,
        scale = 1.50,
        unitSound = "AzureDragon",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "黑幼龙",
        file = "units\\creeps\\BlackDragonWelp\\BlackDragonWelp",
        modelScale = 0.65,
        scale = 1.50,
        unitSound = "AzureDragon",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "青幼龙",
        file = "units\\creeps\\BronzeDragonWelp\\BronzeDragonWelp",
        modelScale = 0.65,
        scale = 1.50,
        unitSound = "AzureDragon",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "绿幼龙",
        file = "units\\creeps\\GreenDragonWelp\\GreenDragonWelp",
        modelScale = 0.65,
        scale = 1.50,
        unitSound = "AzureDragon",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "蓝幼龙",
        file = "units\\creeps\\AzureDragonWelp\\AzureDragonWelp",
        modelScale = 0.65,
        scale = 1.50,
        unitSound = "AzureDragon",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "幽幼龙",
        file = "units\\creeps\\NetherDragon\\NetherDragon",
        modelScale = 0.65,
        scale = 1.50,
        unitSound = "NetherDragon",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "堕落树人",
        file = "units\\creeps\\CorruptedEnt\\CorruptedEnt",
        modelScale = 0.90,
        scale = 1.00,
        unitSound = "CorruptedEnt",
    },
    {
        Name = "埃瑞达男巫",
        file = "units\\demon\\EredarWarlock\\EredarWarlock",
        modelScale = 0.75,
        scale = 1.00,
        unitSound = "PitLord",
    },
    {
        Name = "埃瑞达-信魔者",
        file = "units\\demon\\EredarWarlockPurple\\EredarWarlockPurple",
        modelScale = 0.75,
        scale = 1.00,
        unitSound = "PitLord",
    },
    {
        Name = "无名骗士",
        file = "Units\\Creeps\\FacelessOne\\FacelessOne",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "FacelessOne",
    },
    {
        Name = "狂暴守卫",
        file = "units\\demon\\Felgaurd\\Felgaurd",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "DoomGuard",
    },
    {
        Name = "狂暴领主",
        file = "units\\demon\\FelgaurdBlue\\FelgaurdBlue",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "DoomGuard",
    },
    {
        Name = "狂暴野兽",
        file = "units\\creeps\\FelstalkerPurple\\FelstalkerPurple",
        modelScale = 0.80,
        scale = 1.20,
        unitSound = "Felhound",
    },
    {
        Name = "邪恶漫步者",
        file = "units\\demon\\felhound\\felhound",
        modelScale = 0.90,
        scale = 1.30,
        unitSound = "Felhound",
    },
    {
        Name = "熊怪",
        file = "units\\creeps\\Furbolg\\Furbolg",
        modelScale = 1.15,
        scale = 1.00,
        unitSound = "Furbolg",
    },
    {
        Name = "熊怪萨满",
        file = "units\\creeps\\FurbolgShaman\\FurbolgShaman",
        modelScale = 1.15,
        scale = 1.00,
        unitSound = "Furbolg",
    },
    {
        Name = "熊猫",
        file = "units\\creeps\\FurbolgPanda\\FurbolgPanda",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Furbolg",
    },
    {
        Name = "熊怪追踪者",
        file = "units\\creeps\\FurbolgTracker\\FurbolgTracker",
        modelScale = 1.20,
        scale = 1.00,
        unitSound = "Furbolg",
    },
    {
        Name = "熊怪乌萨战士",
        file = "units\\creeps\\FurbolgElder\\FurbolgElder",
        modelScale = 1.10,
        scale = 1.20,
        unitSound = "Furbolg",
    },
    {
        Name = "幽灵",
        file = "units\\creeps\\BansheeGhost\\BansheeGhost",
        modelScale = 1.05,
        scale = 1.00,
        unitSound = "Ghost",
        movetp = "hover",
        moveHeight = 50,
    },
    {
        Name = "海巨人",
        file = "Units\\Creeps\\SeaGiant\\SeaGiant",
        modelScale = 0.70,
        scale = 1.50,
        unitSound = "SeaGiant",
    },
    {
        Name = "深海巨猎人",
        file = "Units\\Creeps\\SeaGiantGreen\\SeaGiantGreen",
        modelScale = 0.80,
        scale = 2.10,
        unitSound = "SeaGiant",
    },
    {
        Name = "黑蜘蛛",
        file = "units\\creeps\\SpiderBlack\\SpiderBlack",
        modelScale = 1.00,
        scale = 1.10,
        unitSound = "Spider",
    },
    {
        Name = "绿蜘蛛",
        file = "units\\creeps\\SpiderGreen\\SpiderGreen",
        modelScale = 0.60,
        scale = 1.50,
        unitSound = "Spider",
    },
    {
        Name = "毒蜘蛛",
        file = "units\\creeps\\SpiderBlue\\SpiderBlue",
        modelScale = 1.00,
        scale = 1.50,
        unitSound = "Spider",
    },
    {
        Name = "蜘蛛",
        file = "units\\creeps\\Spider\\Spider",
        modelScale = 0.55,
        scale = 1.10,
        unitSound = "Spider",
    },
    {
        Name = "豺狼偷猎者",
        file = "units\\creeps\\GnollArcher\\GnollArcher",
        modelScale = 0.90,
        scale = 1.00,
        unitSound = "GnollArcher",
    },
    {
        Name = "豺狼",
        file = "units\\creeps\\Gnoll\\Gnoll",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Gnoll",
    },
    {
        Name = "豺狼守望者",
        file = "units\\creeps\\GnollWarden\\GnollWarden",
        modelScale = 1.50,
        scale = 1.00,
        unitSound = "Gnoll",
    },
    {
        Name = "豺狼首领",
        file = "units\\creeps\\GnollOverseer\\GnollOverseer",
        modelScale = 1.75,
        scale = 1.00,
        unitSound = "GnollKing",
    },
    {
        Name = "泥潭傀儡",
        file = "units\\creeps\\RockGolem\\RockGolem",
        modelScale = 0.60,
        scale = 1.75,
        unitSound = "RockGolem",
    },
    {
        Name = "傀儡战士",
        file = "units\\creeps\\GolemStatue\\GolemStatue",
        modelScale = 0.80,
        scale = 1.50,
        unitSound = "",
    },
    {
        Name = "女妖侦察者",
        file = "units\\creeps\\Harpy\\Harpy",
        modelScale = 1.00,
        scale = 1.20,
        unitSound = "Harpy",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "鹰身女妖巫婆",
        file = "units\\creeps\\HarpyWitch\\HarpyWitch",
        modelScale = 1.00,
        scale = 1.20,
        unitSound = "Harpy",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "鹰身女王",
        file = "units\\creeps\\HarpyQueen\\HarpyQueen",
        modelScale = 1.10,
        scale = 1.10,
        unitSound = "Harpy",
        movetp = "fly",
        moveHeight = 150,
    },
    {
        Name = "小九头怪蛇",
        file = "Units\\Creeps\\Hydra\\Hydra",
        modelScale = 1.10,
        scale = 1.10,
        unitSound = "AzureDragon",
    },
    {
        Name = "冰魔牧师",
        file = "units\\creeps\\IceTrollShadowPriest\\IceTrollShadowPriest",
        modelScale = 1.05,
        scale = 1.00,
        unitSound = "IceTrollShadowPriest",
    },
    {
        Name = "冰之巨魔",
        file = "units\\creeps\\IceTroll\\IceTroll",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "IceTroll",
    },
    {
        Name = "地狱火机关人",
        file = "units\\creeps\\InfernalCannonCannon\\InfernalCannonCannon",
        modelScale = 0.75,
        scale = 2.25,
        unitSound = "InfernalMachine",
    },
    {
        Name = "地狱火机关人",
        file = "units\\creeps\\InfernalCannonFlame\\InfernalCannonFlame",
        modelScale = 1.50,
        scale = 3.50,
        unitSound = "InfernalMachine",
    },
    {
        Name = "地穴狗头人",
        file = "units\\creeps\\Kobold\\Kobold",
        modelScale = 1.25,
        scale = 1.00,
        unitSound = "Kobold",
    },
    {
        Name = "狗头人占卜者",
        file = "units\\creeps\\KoboldGeomancer\\KoboldGeomancer",
        modelScale = 1.40,
        scale = 1.00,
        unitSound = "Kobold",
    },
    {
        Name = "闪电蜥蜴",
        file = "units\\creeps\\ThunderLizard\\ThunderLizard",
        modelScale = 1.40,
        scale = 1.00,
        unitSound = "KotoBeastNoRider",
    },
    {
        Name = "巨虾",
        file = "Units\\Creeps\\Lobstrokkred\\Lobstrokkred",
        modelScale = 0.55,
        scale = 1.40,
        unitSound = "Lobstrokk",
    },
    {
        Name = "蓝巨虾",
        file = "Units\\Creeps\\Lobstrokkblue\\Lobstrokkblue",
        modelScale = 0.55,
        scale = 1.40,
        unitSound = "Lobstrokk",
    },
    {
        Name = "绿巨虾",
        file = "Units\\Creeps\\Lobstrokkgreen\\Lobstrokkgreen",
        modelScale = 0.55,
        scale = 1.40,
        unitSound = "Lobstrokk",
    },
    {
        Name = "黑暗巫师",
        file = "units\\creeps\\BanditMage\\BanditMage",
        modelScale = 1.20,
        scale = 1.50,
        unitSound = "HeroArchMage",
    },
    {
        Name = "玛格娜托战士",
        file = "Units\\Creeps\\MagnataurBrown\\MagnataurBrown",
        modelScale = 1.13,
        scale = 2.25,
        unitSound = "Magnatanr",
    },
    {
        Name = "玛格娜托撕裂者",
        file = "units\\creeps\\Magnataur\\Magnataur",
        modelScale = 1.33,
        scale = 2.75,
        unitSound = "Magnataur",
    },
    {
        Name = "玛格娜托破坏者",
        file = "units\\creeps\\MagnataurBlue\\MagnataurBlue",
        modelScale = 1.25,
        scale = 2.70,
        unitSound = "Magnataur",
    },
    {
        Name = "冰牙猛犸",
        file = "Units\\Creeps\\Mammoth\\Mammoth",
        modelScale = 1.05,
        scale = 2.10,
        unitSound = "Mammoth",
    },
    {
        Name = "恐怖猛犸",
        file = "units\\creeps\\MammothBlack\\MammothBlack",
        modelScale = 1.15,
        scale = 2.30,
        unitSound = "Mammoth",
    },
    {
        Name = "穆格尔岩人",
        file = "Units\\Creeps\\MurgulTideWarrior\\MurgulTideWarrior",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "murloc",
    },
    {
        Name = "穆格尔血女巫",
        file = "Units\\Creeps\\MurgulBloodGill\\MurgulBloodGill",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "murloc",
    },
    {
        Name = "穆格尔猎人",
        file = "Units\\Creeps\\MurgulShadowCaster\\MurgulShadowCaster",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "murloc",
    },
    {
        Name = "穆格尔掠夺者",
        file = "units\\creeps\\MurgulReaver\\MurgulReaver",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "murloc",
    },
    {
        Name = "两栖追随者",
        file = "units\\creeps\\Murloc\\Murloc",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "murloc",
    },
    {
        Name = "两栖苦难者",
        file = "units\\creeps\\MurlocMutant\\MurlocMutant",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "murloc",
    },
    {
        Name = "两栖人猎手",
        file = "units\\creeps\\MurlocWarrior\\MurlocWarrior",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "murloc",
    },
    {
        Name = "两栖食肉者",
        file = "units\\creeps\\MurlocFlesheater\\MurlocFlesheater",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "murloc",
    },
    {
        Name = "两栖夜行者",
        file = "units\\creeps\\MurlocNightcrawler\\MurlocNightcrawler",
        modelScale = 1.60,
        scale = 1.00,
        unitSound = "murloc",
    },
    {
        Name = "小蜘蛛",
        file = "units\\creeps\\Nerubian\\Nerubian",
        modelScale = 0.60,
        scale = 1.50,
        unitSound = "Nerubian",
    },
    {
        Name = "蛛网怪织网者",
        file = "units\\creeps\\NerubianSpiderLord\\NerubianSpiderLord",
        modelScale = 1.00,
        scale = 2.00,
        unitSound = "Nerubian",
    },
    {
        Name = "蛛网怪女皇",
        file = "units\\creeps\\NerubianQueen\\NerubianQueen",
        modelScale = 1.60,
        scale = 2.00,
        unitSound = "Nerubian",
    },
    {
        Name = "食人鬼",
        file = "units\\creeps\\Ogre\\Ogre",
        modelScale = 1.25,
        scale = 1.20,
        unitSound = "Ogre",
    },
    {
        Name = "食人鬼魔法师",
        file = "units\\creeps\\OgreMagi\\OgreMagi",
        modelScale = 1.40,
        scale = 1.20,
        unitSound = "Ogre",
    },
    {
        Name = "食人鬼大佬",
        file = "units\\creeps\\OgreLord\\OgreLord",
        modelScale = 1.70,
        scale = 2.00,
        unitSound = "Ogre",
    },
    {
        Name = "蛛网怪女皇",
        file = "units\\creeps\\NerubianQueen\\NerubianQueen",
        modelScale = 1.60,
        scale = 2.00,
        unitSound = "Nerubian",
    },
    {
        Name = "迅猛野兽",
        file = "units\\creeps\\Owlbear\\Owlbear",
        modelScale = 1.20,
        scale = 1.60,
        unitSound = "Owlbear",
    },
    {
        Name = "北极熊",
        file = "units\\creeps\\PolarBear\\PolarBear",
        modelScale = 0.95,
        scale = 1.80,
        unitSound = "GrizzlyBear",
    },
    {
        Name = "北极熊怪",
        file = "units\\creeps\\PolarFurbolg\\PolarFurbolg",
        modelScale = 0.90,
        scale = 1.00,
        unitSound = "Furbolg",
    },
    {
        Name = "北极熊怪萨满",
        file = "units\\creeps\\PolarFurbolgTracker\\PolarFurbolgTracker",
        modelScale = 0.90,
        scale = 1.00,
        unitSound = "Furbolg",
    },
    {
        Name = "豪猪",
        file = "units\\creeps\\Bristleback\\Bristleback",
        modelScale = 1.10,
        scale = 1.00,
        unitSound = "Bristleback",
    },
    {
        Name = "尖毛兽侦察兵",
        file = "units\\creeps\\RazorMane\\RazorMane",
        modelScale = 1.20,
        scale = 1.00,
        unitSound = "RazorMane",
    },
    {
        Name = "豪猪猎手",
        file = "units\\creeps\\Bristleback\\Bristleback",
        modelScale = 1.40,
        scale = 1.00,
        unitSound = "Bristleback",
    },
    {
        Name = "尖毛兽医生",
        file = "units\\creeps\\RazorManeChief\\RazorManeChief",
        modelScale = 1.30,
        scale = 1.00,
        unitSound = "RazorMane",
    },
    {
        Name = "潮汐幽灵",
        file = "units\\creeps\\RevenantOfTheWaves\\RevenantOfTheWaves",
        modelScale = 0.90,
        scale = 1.00,
        unitSound = "Revenant",
    },
    {
        Name = "火焰幽魂",
        file = "units\\creeps\\Revenant\\Revenant",
        modelScale = 0.90,
        scale = 1.00,
        unitSound = "Revenant",
    },
    {
        Name = "海之幽灵",
        file = "units\\creeps\\RevenantOfTheWaves\\RevenantOfTheWaves",
        modelScale = 1.05,
        scale = 1.00,
        unitSound = "Revenant",
    },
    {
        Name = "小蜥蜴",
        file = "units\\creeps\\ThunderLizardSalamander\\ThunderLizardSalamander",
        modelScale = 0.60,
        scale = 2.50,
        unitSound = "KotoBeastNoRider",
    },
    {
        Name = "野人",
        file = "units\\creeps\\Sasquatch\\Sasquatch",
        modelScale = 1.00,
        scale = 1.20,
        unitSound = "Wendigo",
    },
    {
        Name = "野人长者",
        file = "units\\creeps\\SasquatchShaman\\SasquatchShaman",
        modelScale = 1.00,
        scale = 1.20,
        unitSound = "Wendigo",
    },
    {
        Name = "赛特斯",
        file = "units\\creeps\\Satyr\\Satyr",
        modelScale = 1.15,
        scale = 1.00,
        unitSound = "Satyr",
    },
    {
        Name = "赛特斯之魔法师",
        file = "units\\creeps\\SatyrTrickster\\SatyrTrickster",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Satyr",
    },
    {
        Name = "赛特斯之地狱使者",
        file = "units\\creeps\\satyrhellcaller\\satyrhellcaller",
        modelScale = 1.05,
        scale = 1.25,
        unitSound = "Satyr",
    },
    {
        Name = "兽族骷髅",
        file = "units\\creeps\\SkeletonOrc\\SkeletonOrc",
        modelScale = 1.10,
        scale = 1.00,
        unitSound = "Skeleton",
    },
    {
        Name = "淤泥战士",
        file = "units\\creeps\\SludgeMonster\\SludgeMonster",
        modelScale = 0.75,
        scale = 1.00,
        unitSound = "SludgeMonster",
    },
    {
        Name = "风暴撕裂者学徒",
        file = "units\\creeps\\OrcWarlock\\OrcWarlock",
        modelScale = 0.90,
        scale = 1.10,
        unitSound = "ShamanX",
    },
    {
        Name = "女妖精",
        file = "units\\demon\\Demoness\\Demoness",
        modelScale = 1.00,
        scale = 1.00,
        unitSound = "Demoness",
    },
    {
        Name = "恶女妖精",
        file = "units\\demon\\DemonessBlue\\DemonessBlue",
        modelScale = 1.20,
        scale = 1.10,
        unitSound = "Demoness",
    },
    {
        Name = "小海龟",
        file = "Units\\Creeps\\SeaTurtleRange\\SeaTurtleRange",
        modelScale = 0.40,
        scale = 1.50,
        unitSound = "GiantSeaTurtle",
    },
    {
        Name = "海龟",
        file = "Units\\Creeps\\SeaTurtle\\SeaTurtle",
        modelScale = 0.50,
        scale = 2.00,
        unitSound = "GiantSeaTurtle",
    },
    {
        Name = "龙龟",
        file = "Units\\Creeps\\DragonSeaTurtle\\DragonSeaTurtle",
        modelScale = 1.00,
        scale = 3.60,
        unitSound = "GiantSeaTurtle",
    },
    {
        Name = "图斯卡尔格斗者",
        file = "Units\\Creeps\\tuskar\\tuskar",
        modelScale = 0.75,
        scale = 1.25,
        unitSound = "Tuskarr",
    },
    {
        Name = "无敌黑暗猎人",
        file = "Units\\Creeps\\Unbroken\\Unbroken",
        modelScale = 0.55,
        scale = 1.25,
        unitSound = "Unbroken",
    },
    {
        Name = "虚无行者",
        file = "units\\creeps\\VoidWalker\\VoidWalker",
        modelScale = 0.75,
        scale = 1.00,
        unitSound = "ObsidianDestroyer",
    },
    {
        Name = "雪怪",
        file = "units\\creeps\\Wendigo\\Wendigo",
        modelScale = 0.95,
        scale = 1.20,
        unitSound = "Wendigo",
    },
    {
        Name = "雪怪长老",
        file = "units\\creeps\\WendigoShaman\\WendigoShaman",
        modelScale = 1.20,
        scale = 1.20,
        unitSound = "Wendigo",
    },
    {
        Name = "大灰狼",
        file = "units\\creeps\\TimberWolf\\TimberWolf",
        modelScale = 0.80,
        scale = 1.20,
        unitSound = "SpiritWolf",
    },
    {
        Name = "恐怖之狼",
        file = "units\\creeps\\DireWolf\\DireWolf",
        modelScale = 1.20,
        scale = 1.30,
        unitSound = "SpiritWolf",
    },
    {
        Name = "骷髅射手",
        file = "units\\creeps\\SkeletonArcher\\SkeletonArcher",
        modelScale = 1.30,
        scale = 1.00,
        unitSound = "SkeletonArcher",
    },
}