items_shahua = {
    {
        Name = "速度之靴",
        Description = "一双平凡但不普通的鞋子",
        Suffix = "",
        goldcost = 500,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNBootsOfSpeed.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            move = "+50",
        },
        Shop = { "沙华铺" }
    },
    {
        Name = "生命护身符",
        Description = "保护生命的护符",
        Suffix = "",
        goldcost = 600,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNPeriapt.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            life = "+1500",
        },
        Shop = { "沙华铺" }
    },
    {
        Name = "守护指环",
        Description = "坚固的指环，可增强防御",
        Suffix = "",
        goldcost = 625,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNRingGreen.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            defend = "+30",
        },
        Shop = { "沙华铺" }
    },
    {
        Name = "恢复指环",
        Description = "附有魔力的指环，能感受到生命力",
        Suffix = "",
        goldcost = 650,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNRingSkull.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            life_back = "+70",
        },
        Shop = { "沙华铺" }
    },
    {
        Name = "火焰风衣",
        Description = "火炎蔓延的风衣，不会烧伤自己却能烧伤附近的敌人",
        PSDescription = "每秒对周围180范围的敌人造成45点的伤害",
        Suffix = "",
        goldcost = 800,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNCloakOfFlames.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            natural_fire_oppose = "+5",
        },
        Shop = { "沙华铺" }
    },
    {
        Name = "影子风衣",
        ASDescription = "隐身5秒",
        Description = "神奇的风衣，能令人透明",
        Suffix = "",
        goldcost = 800,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNCloak.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            move = "+25",
        },
        Shop = { "沙华铺" }
    },
    {
        Name = "闪避护符",
        Description = "从法师祈求得来的护符，报人平安",
        Suffix = "",
        goldcost = 1200,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNTalisman.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            avoid = "+10",
        },
        Shop = { "沙华铺" }
    },
    {
        Name = "神秘腰带",
        Description = "神秘的腰带，对法术有抵抗力",
        Suffix = "",
        goldcost = 1600,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNRunedBracers.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            resistance = "+10",
        },
        Shop = { "沙华铺" }
    },
    {
        Name = "邪念牌",
        Description = "邪念纠缠的木牌，能感受到怨念",
        Suffix = "",
        goldcost = 2100,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNBloodLust.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            attack_speed = "+40",
            move = "+30",
            hemophagia = "+15",
            defend = "-10",
        },
        Shop = { "沙华铺" }
    },
    {
        Name = "时间震荡器",
        PSDescription = "释放技能时有1%几率重置冷却时间",
        Description = "不起眼的科技产物，有重置时间的神奇效果",
        Suffix = "",
        goldcost = 3800,
        lumbercost = 0,
        Art = "war3mapImported\\INV_Gizmo_01.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = nil,
        Shop = { "沙华铺" }
    },
    {
        Name = "重生十字架",
        PSDescription = "在英雄死后10秒自动让其复活",
        Description = "(可用碎裂轮回装载)",
        Suffix = "",
        goldcost = 5000,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNAnkh.blp",
        powerup = 0,
        sellable = 0,
        pawnable = 1,
        droppable = 1,
        Attr = nil,
        Shop = { "沙华铺" }
    },

}