items_mi = {
    {
        Name = "秘·魂",
        Description = "发出赤铜的光，似乎完全没用的东西",
        Suffix = "隐藏装备 - 碎片 - 魂",
        goldcost = 0,
        lumbercost = 0,
        Art = "war3mapImported\\INV_Ingot_09.blp",
        powerup = 0,
        sellable = 0,
        pawnable = 0,
        droppable = 1,
        Attr = {
            attack_white = "+1",
            attack_green = "+1",
        },
    },
    {
        Name = "秘·之",
        Description = "发出幽蓝的光，似乎完全没用的东西",
        Suffix = "隐藏装备 - 碎片 - 之",
        goldcost = 0,
        lumbercost = 0,
        Art = "war3mapImported\\INV_Ingot_10.blp",
        powerup = 0,
        sellable = 0,
        pawnable = 0,
        droppable = 1,
        Attr = {
            knocking = "+1",
            violence = "+1",
        },
    },
    {
        Name = "秘·似",
        Description = "发出暗紫的光，似乎完全没用的东西",
        Suffix = "隐藏装备 - 碎片 - 似",
        goldcost = 0,
        lumbercost = 0,
        Art = "war3mapImported\\INV_Ingot_11.blp",
        powerup = 0,
        sellable = 0,
        pawnable = 0,
        droppable = 1,
        Attr = {
            attack_speed = "+1",
        },
    },
    {
        Name = "秘·光",
        Description = "发出白色的光，似乎完全没用的东西",
        Suffix = "隐藏装备 - 碎片 - 光",
        goldcost = 0,
        lumbercost = 0,
        Art = "war3mapImported\\INV_Ingot_Adamantite.blp",
        powerup = 0,
        sellable = 0,
        pawnable = 0,
        droppable = 1,
        Attr = {
            hemophagia = "+1",
            defend = "+1",
        },
    },
    {
        Name = "秘·魂之似光",
        Description = "传说中的神武",
        ASDescription = "瞬间增加100%物理和魔法暴击几率10秒",
        Suffix = "隐藏装备 - 魂之似光",
        goldcost = 0,
        lumbercost = 0,
        Art = "war3mapImported\\INV_Staff_83.blp",
        powerup = 0,
        sellable = 0,
        pawnable = 0,
        droppable = 1,
        cooldownID = 60,
        Attr = {
            attack_white = "+999",
            attack_green = "+999",
            defend = "+200",
            resistance = "+30",
            toughness = "+175",
            attack_speed = "+100",
            hemophagia = "+75",
            knocking = "+25",
            violence = "+25",
            knocking_odds = "+35",
            violence_odds = "+35",
        },
    },
}