items_canghai = {
    {
        Name = "短剑",
        Description = "铁制短剑，沉重且不太锋利",
        Suffix = nil,
        goldcost = 300,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNSteelMelee.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            attack_white = "+50",
        },
        Shop = { "沧海坊" }
    },
    {
        Name = "匕首",
        Description = "锋利的匕首，见血封喉",
        Suffix = nil,
        goldcost = 300,
        lumbercost = 0,
        Art = "war3mapImported\\INV_ThrowingKnife_02.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            attack_white = "+30",
            hemophagia = "+5",
            aim = "+5",
        },
        Shop = { "沧海坊" }
    },
    {
        Name = "加速手套",
        Description = "套上手套能增强摩擦力，更易攻击",
        Suffix = nil,
        goldcost = 475,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNGlove.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            attack_speed = "+15",
        },
        Shop = { "沧海坊" }
    },
    {
        Name = "钢斧",
        Description = "极其沉重的斧头，攻击力很高",
        Suffix = nil,
        goldcost = 600,
        lumbercost = 0,
        Art = "war3mapImported\\INV_Axe_17.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            attack_white = "+120",
            knocking = "+5",
            knocking_odds = "+3",
            attack_speed = "-10",
        },
        Shop = { "沧海坊" }
    },
    {
        Name = "法杖",
        Description = "百年树木削成的木杖，有一点点法力",
        Suffix = nil,
        goldcost = 750,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNWitchDoctorAdept.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            attack_green = "+125",
            resistance = "+3",
            mana_back = "+3.5",
        },
        Shop = { "沧海坊" }
    },
    {
        Name = "力量手套",
        Description = "食人鬼的力量手套",
        Suffix = nil,
        goldcost = 1000,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNGauntletsOfOgrePower.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            str_green = "+45",
        },
        Shop = { "沧海坊" }
    },
    {
        Name = "敏捷鞋套",
        Description = "蜘蛛丝编织的鞋套，穿上非常敏捷",
        Suffix = nil,
        goldcost = 1000,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNSlippersOfAgility.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            agi_green = "+45",
        },
        Shop = { "沧海坊" }
    },
    {
        Name = "智力斗篷",
        Description = "初级法师的斗篷",
        Suffix = nil,
        goldcost = 1000,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNMantleOfIntelligence.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            int_green = "+45",
        },
        Shop = { "沧海坊" }
    },
    {
        Name = "吸血面具",
        Description = "古怪的面具，戴上的人嗜血如命",
        Suffix = nil,
        goldcost = 1100,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNMaskOfDeath.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            hemophagia = "+25",
            hemophagia_skill = "+25",
        },
        Shop = { "沧海坊" }
    },
    {
        Name = "狮鹫之月（沉睡）",
        Description = "狮鹫士兵手上的月形枪",
        Suffix = nil,
        goldcost = 1750,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNAdvancedStrengthOfTheMoon.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            attack_white = "+100",
            attack_green = "+100",
        },
        Shop = { "沧海坊" }
    },
    {
        Name = "狮鹫之月（觉醒）",
        Description = "狮鹫士兵手上的月形枪，饮血而觉醒",
        Suffix = nil,
        goldcost = 2000,
        lumbercost = 0,
        Art = "war3mapImported\\INV_Staff_31.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            attack_white = "+155",
            attack_green = "+185",
            aim = "+10",
        },
    },
    {
        Name = "金环",
        Description = "黄金铸造的环",
        Suffix = nil,
        goldcost = 2000,
        lumbercost = 0,
        Art = "ReplaceableTextures\\CommandButtons\\BTNGoldRing.blp",
        powerup = 0,
        sellable = 1,
        pawnable = 1,
        droppable = 1,
        Attr = {
            toughness = "+30",
            attack_speed = "+50",
        },
        Shop = { "沧海坊" }
    },
}