shopsAbility = {
    {
        id = "ACnr",
        Name = "生命恢复光环",
        DataA1 = 0.03,
        BelongTo = { "婲開ぃ誰獨賞〆之泉" },
        Targs1 = "air,allies,friend,ground,vulnerable,organic,self,invulnerable",
        Area1 = 500,
    },
    {
        id = "ANre",
        Name = "魔法恢复光环",
        DataA1 = 0.04,
        BelongTo = { "婲開ぃ誰獨賞〆之泉" },
        Targs1 = "air,allies,friend,ground,vulnerable,organic,self,invulnerable",
        Area1 = 500,
    },
}

shops = {
    {
        Name = "婲開ぃ誰獨賞〆之泉",
        pathTex = "PathTextures\\8x8SimpleSolid.tga",
        abilList = "",
        file = "buildings\\other\\FountainOfLifeBlood\\FountainOfLifeBlood.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNFountainOfLife.blp",
        modelScale = 0.70,
        scale = 3.20,
        HP = 99999,
        sight = 800,
        nsight = 800,
    },
    {
        Name = "沧海坊",
        pathTex = "PathTextures\\8x8SimpleSolid.tga",
        abilList = "Aneu,Apit",
        file = "buildings\\orc\\WarMill\\WarMill",
        Art = "ReplaceableTextures\\CommandButtons\\BTNForge.blp",
        modelScale = 1.00,
        scale = 4.20,
        HP = 99999,
        sight = 800,
        nsight = 800,
    },
    {
        Name = "沙华铺",
        pathTex = "PathTextures\\8x8SimpleSolid.tga",
        abilList = "Aneu,Apit",
        file = "buildings\\nightelf\\HuntersHall\\HuntersHall.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNHuntersHall.blp",
        modelScale = 1.00,
        scale = 4.20,
        HP = 99999,
        sight = 800,
        nsight = 800,
    },
    {
        Name = "小鬼珍宝市场",
        pathTex = "PathTextures\\8x8SimpleSolid.tga",
        abilList = "Aneu,Apit",
        file = "buildings\\orc\\VoodooLounge\\VoodooLounge",
        Art = "ReplaceableTextures\\CommandButtons\\BTNVoodooLounge.blp",
        modelScale = 1.00,
        scale = 4.20,
        HP = 99999,
        sight = 800,
        nsight = 800,
    },
    {
        Name = "符文镶嵌室",
        pathTex = "PathTextures\\8x8SimpleSolid.tga",
        abilList = "Aneu,Apit",
        file = "buildings\\orc\\VoodooLounge\\VoodooLounge",
        Art = "ReplaceableTextures\\CommandButtons\\BTNArcaneVault.blp",
        modelScale = 1.00,
        scale = 4.20,
        HP = 99999,
        sight = 800,
        nsight = 800,
    },
    {
        Name = "奇魂书塔",
        pathTex = "",
        abilList = "Aneu,Apit",
        file = "buildings\\human\\ArcaneVault\\ArcaneVault",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGraveyard.blp",
        modelScale = 1.50,
        scale = 1.70,
        HP = 99999,
        sight = 500,
        nsight = 500,
    },
    {
        Name = "小柒灵药店",
        pathTex = "",
        abilList = "Aneu,Apit",
        file = "buildings\\human\\ArcaneVault\\ArcaneVault",
        Art = "ReplaceableTextures\\CommandButtons\\BTNGraveyard.blp",
        modelScale = 1.50,
        scale = 1.70,
        HP = 99999,
        sight = 500,
        nsight = 500,
    },
}