towerRaces = {
    {
        Name = "人类",
        Ubertip = "平凡而多彩的种族",
        Text = "+1力量|n+1智力",
        Art = "war3mapImported\\icon_race_human.blp",
    },
    {
        Name = "人王",
        Ubertip = "成就巅峰的凡人们",
        Text = "+2力量|n+2智力",
        Art = "war3mapImported\\icon_race_human2.blp",
    },
    {
        Name = "矮人",
        Ubertip = "极具创造力的种族",
        Text = "+2智力",
        Art = "war3mapImported\\icon_race_dwraf.blp",
    },
    {
        Name = "血精灵",
        Ubertip = "为了复兴辛多雷的荣耀而努力",
        Text = "+2魔法攻击",
        Art = "war3mapImported\\icon_race_elf.blp",
    },
    {
        Name = "兽人",
        Ubertip = "暴躁、野蛮，倾向于先行动再思考",
        Text = "+3物理攻击",
        Art = "war3mapImported\\icon_race_orc.blp",
    },
    {
        Name = "巨魔",
        Ubertip = "和精灵曾经有过一场生死之战",
        Text = "+1敏捷",
        Art = "war3mapImported\\icon_race_troll.blp",
    },
    {
        Name = "牛头人",
        Ubertip = "以勇猛和骄傲著称,会使用他们巨大的图滕柱将敌人砸成肉泥",
        Text = "+1%物理暴击伤害",
        Art = "war3mapImported\\icon_race_tauren.blp",
    },
    {
        Name = "暗夜精灵",
        Ubertip = "很多妹子的种族",
        Text = "+1%魔法暴击伤害",
        Art = "war3mapImported\\icon_race_nightelf.blp",
    },
    {
        Name = "德鲁伊",
        Ubertip = "行踪隐秘，神秘莫测",
        Text = "+3魔法攻击",
        Art = "war3mapImported\\icon_race_druid.blp",
    },
    {
        Name = "亡灵",
        Ubertip = "看上去像是死了，其实是被净化了",
        Text = "+1护甲",
        Art = "war3mapImported\\icon_race_undead.blp",
    },
    {
        Name = "娜迦",
        Ubertip = "一般都长得像条蛇",
        Text = "+0.5%水攻击",
        Art = "war3mapImported\\icon_race_naga.blp",
    },
    {
        Name = "元素",
        Ubertip = "自然界中的聚合物，形成了意识的神奇存在",
        Text = "+0.3%魔抗",
        Art = "war3mapImported\\icon_race_elemental.blp",
    },
    {
        Name = "恶魔",
        Ubertip = "拥有超自然力量的邪恶存在代表",
        Text = "+2敏捷",
        Art = "war3mapImported\\icon_race_demon.blp",
    },
    {
        Name = "昆虫",
        Ubertip = "一般都长得很吓人或很丑",
        Text = "+1减伤",
        Art = "war3mapImported\\icon_race_insect.blp",
    },
    {
        Name = "异兽",
        Ubertip = "特别的怪兽，来自未知的领域",
        Text = "+1力量|n+1敏捷|n+1智力",
        Art = "war3mapImported\\icon_race_rareanimals.blp",
    },
    {
        Name = "幽魂",
        Ubertip = "死去的灵魂",
        Text = "+0.3%回避",
        Art = "war3mapImported\\icon_race_ghost.blp",
    },
    {
        Name = "食人魔",
        Ubertip = "丑陋又贪婪的人型生物，天性邪恶",
        Text = "+1敏捷",
        Art = "war3mapImported\\icon_race_ogre.blp",
    },
    {
        Name = "地精",
        Ubertip = "善于经商贸易的种族",
        Text = "+2智力",
        Art = "war3mapImported\\icon_race_goblin.blp",
    },
    {
        Name = "龙人",
        Ubertip = "拥有龙之力量的战士",
        Text = "+0.3%攻击速度",
        Art = "war3mapImported\\icon_race_dragon.blp",
    },
    {
        Name = "熊猫",
        Ubertip = "古老国度的神奇生物",
        Text = "+3力量",
        Art = "war3mapImported\\icon_race_panda.blp",
    },
}
