towerRaces = {
    {
        Name = "人类",
        Ubertip = "平凡而多彩的种族",
        Text = "+7%力量|n+7%敏捷|n+7%智力",
        Art = "war3mapImported\\icon_race_human.blp",
    },
    {
        Name = "人王",
        Ubertip = "成就巅峰的人们",
        Text = "+15%力量|n+15%敏捷|n+15%智力",
        Art = "war3mapImported\\icon_race_human2.blp",
    },
    {
        Name = "矮人",
        Ubertip = "极具奇妙特色的种族",
        Text = "+15%命中",
        Art = "war3mapImported\\icon_race_dwraf.blp",
    },
    {
        Name = "血精灵",
        Ubertip = "为了复兴辛多雷的荣耀而努力",
        Text = "+10%魔法攻击",
        Art = "war3mapImported\\icon_race_elf.blp",
    },
    {
        Name = "兽人",
        Ubertip = "暴躁、野蛮，倾向于先行动再思考",
        Text = "+10%物理攻击",
        Art = "war3mapImported\\icon_race_orc.blp",
    },
    {
        Name = "巨魔",
        Ubertip = "和精灵曾经有过一场生死之战",
        Text = "攻击时+5%攻击速度，持续6秒",
        Art = "war3mapImported\\icon_race_troll.blp",
    },
    {
        Name = "牛头人",
        Ubertip = "以勇猛和骄傲著称,会使用他们巨大的图滕柱将敌人砸成肉泥",
        Text = "+7%物理暴击几率",
        Art = "war3mapImported\\icon_race_tauren.blp",
    },
    {
        Name = "暗夜精灵",
        Ubertip = "很多妹子的种族",
        Text = "+暗攻击特性",
        Art = "war3mapImported\\icon_race_nightelf.blp",
    },
    {
        Name = "德鲁伊",
        Ubertip = "行踪隐秘，神秘莫测",
        Text = "+木攻击特性",
        Art = "war3mapImported\\icon_race_druid.blp",
    },
    {
        Name = "亡灵",
        Ubertip = "亡灵不会死亡，消失的亡灵实际上是被净化了",
        Text = "攻击时，敌军-15点移动速度，持续3秒",
        Art = "war3mapImported\\icon_race_undead.blp",
    },
    {
        Name = "娜迦",
        Ubertip = "一般都长得像条蛇，有的自称为龙",
        Text = "+水攻击特性",
        Art = "war3mapImported\\icon_race_naga.blp",
    },
    {
        Name = "元素",
        Ubertip = "自然界中的聚合物，形成了意识的神奇存在",
        Text = "+5%所有自然抗性",
        Art = "war3mapImported\\icon_race_elemental.blp",
    },
    {
        Name = "恶魔",
        Ubertip = "拥有超自然力量的邪恶存在代表",
        Text = "+6%伤害增幅|n+6%攻击速度|n-6点护甲",
        Art = "war3mapImported\\icon_race_demon.blp",
    },
    {
        Name = "昆虫",
        Ubertip = "一般都长得很吓人或很丑",
        Text = "+虫攻击特性",
        Art = "war3mapImported\\icon_race_insect.blp",
    },
    {
        Name = "异兽",
        Ubertip = "特别的怪兽，来自未知的领域",
        Text = "+10%魔抗|n+30点减伤",
        Art = "war3mapImported\\icon_race_rareanimals.blp",
    },
    {
        Name = "幽魂",
        Ubertip = "不肯承认自己已死去的灵魂",
        Text = "+10%回避",
        Art = "war3mapImported\\icon_race_ghost.blp",
    },
    {
        Name = "食人魔",
        Ubertip = "丑陋又贪婪的人型生物，天性邪恶",
        Text = "攻击时，+10%几率眩晕1秒",
        Art = "war3mapImported\\icon_race_ogre.blp",
    },
    {
        Name = "地精",
        Ubertip = "善于经商贸易的种族",
        Text = "+10%智力",
        Art = "war3mapImported\\icon_race_goblin.blp",
    },
    {
        Name = "龙人",
        Ubertip = "拥有龙之力量的战士",
        Text = "+龙攻击特性",
        Art = "war3mapImported\\icon_race_dragon.blp",
    },
    {
        Name = "熊猫",
        Ubertip = "古老国度的神奇生物",
        Text = "+10%力量",
        Art = "war3mapImported\\icon_race_panda.blp",
    },
}
