units = {
    {
        Name = "大精灵",
        abilList = "",
        file = "units\\nightelf\\Wisp\\Wisp",
        Art = "ReplaceableTextures\\CommandButtons\\BTNWisp.blp",
        modelScale = 3,
        scale = 4.00,
        HP = 1000,
        spd = 0,
        sight = 2400,
        nsight = 2400,
        unitSound = "Wisp",
        weapsOn = 0,
    },
    {
        Name = "光辉城主",
        abilList = "",
        file = "war3mapImported\\unit_ReworkedFlameKnight.blp",
        Art = "ReplaceableTextures\\CommandButtons\\BTNWisp.blp",
        modelScale = 2,
        scale = 3.00,
        HP = 5000,
        spd = 0,
        sight = 2400,
        nsight = 2400,
        unitSound = "Uther",
        weapsOn = 0,
    },
    {
        Name = "河草",
        abilList = "Avul,Aloc",
        file = "Doodads\\LordaeronSummer\\Plants\\RiverRushes\\RiverRushes2.mdl",
        Art = "ReplaceableTextures\\WorldEditUI\\Doodad-Environment.blp",
        modelScale = 1,
        scale = 1.00,
        HP = 100,
        spd = 0,
        sight = 0,
        nsight = 0,
        unitSound = "",
        weapsOn = 0,
    },
    {
        Name = "空位",
        abilList = "Avul,Aloc",
        file = "Abilities\\Spells\\NightElf\\TrueshotAura\\TrueshotAura.mdl",
        Art = "ReplaceableTextures\\CommandButtons\\BTNSpellStealOn.blp",
        modelScale = 1,
        scale = 1.60,
        HP = 100,
        spd = 0,
        sight = 0,
        nsight = 0,
        unitSound = "",
        weapsOn = 0,
    }
}